import type { Question } from '../types';

export const BUSINESS: Question[] = [
  // ── Task 1: Governance ───────────────────────────────────────────
  {
    id: 'be1-01', domain: 'business', task: 1, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'What is the PRIMARY purpose of project governance?',
    options: [
      'To provide the framework of structure, decision rights, and oversight for the project',
      'To write the detailed schedule',
      'To manage team conflicts',
      'To perform quality inspections',
    ],
    answer: 0,
    explanation: 'Governance sets the structure, rules, decision-making authority, escalation paths, and oversight that guide the project.',
  },
  {
    id: 'be1-02', domain: 'business', task: 1, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A cost variance of 8% occurs. The governance plan says variances over 10% must be escalated to the steering committee. What should the project manager do?',
    options: [
      'Escalate immediately to the steering committee',
      'Manage the variance within the project manager\'s authority and keep monitoring it against the threshold',
      'Ignore the variance',
      'Ask the team to absorb it with overtime',
    ],
    answer: 1,
    explanation: 'Escalation thresholds define decision rights. Below the threshold, the project manager handles it but keeps monitoring the trend.',
  },
  {
    id: 'be1-03', domain: 'business', task: 1, approach: 'predictive', difficulty: 2, type: 'match',
    stem: 'Match each governance element to its role.',
    left: ['Steering committee', 'PMO', 'Change control board', 'Sponsor'],
    right: [
      'Provides strategic direction and major decisions',
      'Standardizes processes and supports projects',
      'Reviews and approves or rejects change requests',
      'Champions the project and provides funding',
    ],
    explanation: 'Each governance body has defined decision rights and responsibilities within the governance framework.',
  },
  {
    id: 'be1-04', domain: 'business', task: 1, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'An organization moving to agile asks how to keep governance without slowing teams down. What is the BEST recommendation?',
    options: [
      'Require approval of every user story by the steering committee',
      'Use lightweight governance: clear outcome-based success metrics, regular reviews of working product, and defined escalation thresholds',
      'Remove all governance',
      'Use the same phase-gate documents as before',
    ],
    answer: 1,
    explanation: 'Adaptive governance focuses on outcomes, transparency (reviews), and clear thresholds rather than heavy upfront document approval.',
  },
  {
    id: 'be1-05', domain: 'business', task: 1, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which of these is an organizational process asset (OPA)?',
    options: ['Templates and lessons learned repository', 'Government regulations', 'Market conditions', 'Organizational culture'],
    answer: 0,
    explanation: 'OPAs are plans, processes, policies, templates, and knowledge bases internal to the organization. Regulations, market conditions, and culture are enterprise environmental factors (EEFs).',
  },
  {
    id: 'be1-06', domain: 'business', task: 1, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A sponsor asks the project manager to report a milestone as "complete" to the board although testing is not done. What should the project manager do?',
    options: [
      'Report it as complete to keep the sponsor happy',
      'Report the accurate status, and explain the risk and plan to the sponsor',
      'Delay the board report',
      'Report it complete and finish testing quietly later',
    ],
    answer: 1,
    explanation: 'PMI\'s Code of Ethics requires honesty. Governance depends on accurate reporting. Address the sponsor\'s concern with facts and a plan.',
  },
  {
    id: 'be1-07', domain: 'business', task: 1, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'At project start, how should success metrics be defined?',
    options: [
      'Only as on-time and on-budget',
      'As measurable criteria agreed with key stakeholders, linked to business objectives and value',
      'By the project team alone',
      'After the project closes',
    ],
    answer: 1,
    explanation: 'The ECO lists defining success metrics as part of governance. They should be measurable, agreed, and tied to value, not just the triple constraint.',
  },
  {
    id: 'be1-08', domain: 'business', task: 1, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A team member discovers a supplier offering the project manager personal gifts in exchange for preferred treatment. What should the project manager do?',
    options: [
      'Accept gifts below a small value',
      'Decline, disclose the conflict according to organizational policy, and keep procurement fair',
      'Accept and stay neutral',
      'Ignore the issue',
    ],
    answer: 1,
    explanation: 'Ethics and policies are part of governance. Conflicts of interest must be avoided and disclosed (PMI Code of Ethics: fairness and honesty).',
  },

  // ── Task 2: Compliance ───────────────────────────────────────────
  {
    id: 'be2-01', domain: 'business', task: 2, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'When should compliance requirements (e.g., data privacy laws) be identified?',
    options: ['During planning, and revisited throughout the project', 'Only at final acceptance', 'After an audit finding', 'Only if the customer asks'],
    answer: 0,
    explanation: 'Compliance requirements are identified early and monitored continuously because they shape scope, quality, and risk.',
  },
  {
    id: 'be2-02', domain: 'business', task: 2, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A new data privacy regulation takes effect mid-project. Some features process personal data. What should the project manager do FIRST?',
    options: [
      'Continue as planned until an auditor raises it',
      'Assess the regulation\'s impact on the product and backlog with compliance experts',
      'Stop the project',
      'Ask developers to encrypt everything without analysis',
    ],
    answer: 1,
    explanation: 'Confirm the compliance requirements and assess their impact first, then decide on actions (backlog changes, controls, change requests).',
  },
  {
    id: 'be2-03', domain: 'business', task: 2, approach: 'predictive', difficulty: 2, type: 'multi',
    stem: 'Which TWO are potential consequences of noncompliance the project manager should analyze?',
    options: ['Fines and legal penalties', 'Reputational damage', 'Higher team velocity', 'Lower communication channels', 'Faster approvals'],
    answer: [0, 1],
    explanation: 'Noncompliance can lead to fines, legal action, reputational harm, and project stoppage.',
  },
  {
    id: 'be2-04', domain: 'business', task: 2, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'How can an agile team ensure regulatory compliance without a big audit at the end?',
    options: [
      'Add compliance criteria to the Definition of Done and acceptance criteria, and involve compliance in reviews',
      'Skip compliance until the final release',
      'Assign compliance to a separate team after release',
      'Rely on users to report issues',
    ],
    answer: 0,
    explanation: 'Building compliance into DoD and acceptance criteria, with compliance stakeholders reviewing increments, catches gaps continuously.',
  },
  {
    id: 'be2-05', domain: 'business', task: 2, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A compliance audit shows the project meets 92% of required health and safety controls. Two gaps are high severity. What should the project manager do?',
    options: [
      'Report 92% as a pass',
      'Prioritize corrective actions for the high-severity gaps, assign owners, and track to closure',
      'Wait for the next audit',
      'Remove the controls from the requirements',
    ],
    answer: 1,
    explanation: 'Measuring the level of compliance means acting on gaps by severity. High-severity safety gaps need prompt corrective action and tracking.',
  },
  {
    id: 'be2-06', domain: 'business', task: 2, approach: 'predictive', difficulty: 1, type: 'match',
    stem: 'Match each compliance category to an example.',
    left: ['Security', 'Health and safety', 'Sustainability', 'Regulatory'],
    right: [
      'Access controls on customer data',
      'Protective equipment on site',
      'Carbon emissions reporting',
      'Industry licensing requirements',
    ],
    explanation: 'The ECO lists these as compliance categories the project manager must confirm and classify.',
  },
  {
    id: 'be2-07', domain: 'business', task: 2, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'The team wants to use a new AI coding assistant. Company policy restricts sending source code to external services. What should the project manager do?',
    options: [
      'Allow it; productivity is more important',
      'Check the tool against security and data policies with the right stakeholders before use',
      'Ban all tools permanently',
      'Let each developer decide',
    ],
    answer: 1,
    explanation: 'Potential threats to compliance (e.g., data leakage via AI tools) must be assessed against policy before adoption.',
  },
  {
    id: 'be2-08', domain: 'business', task: 2, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A subcontractor\'s work fails an environmental regulation inspection. Who is ultimately responsible for ensuring the project meets the regulation?',
    options: [
      'Only the subcontractor',
      'The performing organization and project manager remain accountable; compliance requirements should have flowed down through the contract',
      'The regulator',
      'The end customer',
    ],
    answer: 1,
    explanation: 'Outsourcing work does not outsource accountability. Compliance obligations should be in contracts, and the project must verify them.',
  },

  // ── Task 3: Change control ───────────────────────────────────────
  {
    id: 'be3-01', domain: 'business', task: 3, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'A stakeholder requests a change to an approved deliverable. What should the project manager do FIRST?',
    options: [
      'Implement the change',
      'Evaluate the impact of the change on scope, schedule, cost, quality, and risk',
      'Reject the change',
      'Send it straight to the CCB without analysis',
    ],
    answer: 1,
    explanation: 'Standard sequence: evaluate impact → identify options → submit change request → CCB decision → update plans → communicate.',
  },
  {
    id: 'be3-02', domain: 'business', task: 3, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'On an agile project, how is a new feature request from a stakeholder typically handled?',
    options: [
      'Submitted to a change control board',
      'Added to the product backlog and prioritized by the product owner',
      'Inserted into the current sprint immediately',
      'Rejected until the next release',
    ],
    answer: 1,
    explanation: 'Agile welcomes change through the backlog. The product owner prioritizes it, usually for a future sprint, without disrupting the current sprint goal.',
  },
  {
    id: 'be3-03', domain: 'business', task: 3, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'The CCB approves a change. What should the project manager do NEXT?',
    options: [
      'Update the project management plan and documents, implement the change, and communicate it to stakeholders',
      'Close the change request without action',
      'Wait for the next phase',
      'Ask the CCB to implement it',
    ],
    answer: 0,
    explanation: 'After approval: update baselines and documents, direct implementation, and communicate the status to affected stakeholders.',
  },
  {
    id: 'be3-04', domain: 'business', task: 3, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A senior executive tells a developer to add a feature directly, bypassing change control. The developer asks the project manager what to do. What should the project manager do?',
    options: [
      'Tell the developer to do it since it is an executive',
      'Meet the executive to explain the change process and help submit and evaluate the change request',
      'Report the executive to HR',
      'Add the feature secretly',
    ],
    answer: 1,
    explanation: 'All changes go through the change control process regardless of who requests them. The project manager helps the executive use it.',
  },
  {
    id: 'be3-05', domain: 'business', task: 3, approach: 'predictive', difficulty: 2, type: 'dropdown',
    stem: 'Complete the change control statement.',
    text: 'Approved changes are recorded in the {0}, and once implemented, the {1} are updated to reflect them.',
    blanks: [
      { options: ['change log', 'issue log', 'risk register'], answer: 0 },
      { options: ['baselines and project documents', 'OPAs only', 'contracts only'], answer: 0 },
    ],
    explanation: 'The change log records all change requests and their status. Approved changes update baselines and the related documents.',
  },
  {
    id: 'be3-06', domain: 'business', task: 3, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'Mid-sprint, the product owner wants to replace the sprint goal because of an urgent market opportunity. What should happen?',
    options: [
      'The team silently adds the new work on top',
      'The product owner may cancel the sprint if the goal becomes obsolete; otherwise, add the new item to the backlog for next sprint',
      'The scrum master decides',
      'The team works double shifts',
    ],
    answer: 1,
    explanation: 'Sprint goals are protected. If the goal is obsolete, the product owner may cancel the sprint. Otherwise, new work goes to the backlog.',
  },
  {
    id: 'be3-07', domain: 'business', task: 3, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A change request was rejected by the CCB. What should the project manager do?',
    options: [
      'Implement it anyway if the team agrees',
      'Update the change log and communicate the decision and rationale to the requester',
      'Delete the request',
      'Resubmit it every week until approved',
    ],
    answer: 1,
    explanation: 'Communicating the status of proposed changes, including rejections, is an explicit ECO enabler.',
  },
  {
    id: 'be3-08', domain: 'business', task: 3, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A team member fixes a defect in a deliverable that was already approved, without telling anyone. Why is this a problem?',
    options: [
      'Defect repairs never need any control',
      'Changes to controlled deliverables must be tracked through configuration and change management to keep baselines and documentation accurate',
      'It wastes time',
      'Only the sponsor can fix defects',
    ],
    answer: 1,
    explanation: 'Even corrective changes to controlled items should follow configuration and change control so that versions, documents, and stakeholders stay aligned.',
  },

  // ── Task 4: Impediments & issues ─────────────────────────────────
  {
    id: 'be4-01', domain: 'business', task: 4, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'A developer mentions in the daily standup that they are blocked waiting for database access. What should the project manager / scrum master do?',
    options: [
      'Tell the developer to wait',
      'Take ownership of removing the impediment after the standup',
      'Solve it during the standup with the whole team',
      'Report it at the end of the sprint',
    ],
    answer: 1,
    explanation: 'Servant leaders remove impediments. Follow up after the standup so the meeting stays short and focused.',
  },
  {
    id: 'be4-02', domain: 'business', task: 4, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A risk identified in the risk register (supplier delay) has now occurred. What should the project manager do?',
    options: [
      'Update the risk register only',
      'Implement the planned risk response, log it as an issue, and track resolution',
      'Ignore it until the next review',
      'Create a new risk',
    ],
    answer: 1,
    explanation: 'When a risk occurs it becomes an issue. Execute the planned response and track it in the issue log.',
  },
  {
    id: 'be4-03', domain: 'business', task: 4, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'The team has five open impediments. Which should the project manager address FIRST?',
    options: [
      'The one blocking the most valuable work in the current sprint',
      'The oldest one',
      'The easiest one',
      'The one reported by the most senior person',
    ],
    answer: 0,
    explanation: 'Prioritize impediments by their impact on value delivery and flow.',
  },
  {
    id: 'be4-04', domain: 'business', task: 4, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'What is the difference between a risk and an issue?',
    options: [
      'A risk is an uncertain future event; an issue is a current condition that needs resolution',
      'They are the same',
      'An issue is always positive',
      'A risk is always negative',
    ],
    answer: 0,
    explanation: 'Risks are uncertain and may happen. Issues have already happened and need action.',
  },
  {
    id: 'be4-05', domain: 'business', task: 4, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'An issue that affects two other projects cannot be resolved within the project manager\'s authority. What should the project manager do?',
    options: [
      'Keep working on it alone',
      'Collaborate with the affected project managers and escalate through the governance path with options and impact analysis',
      'Ignore it since it affects others too',
      'Ask the team to vote',
    ],
    answer: 1,
    explanation: 'Collaborating with stakeholders and using defined escalation paths, bringing analysis and options, is the right approach for cross-project issues.',
  },
  {
    id: 'be4-06', domain: 'business', task: 4, approach: 'agile', difficulty: 2, type: 'multi',
    stem: 'Which TWO actions help ensure impediments are continually addressed?',
    options: [
      'Maintain a visible impediment board',
      'Review open impediments regularly, e.g., daily, and reassess their impact',
      'Only discuss impediments at the final retrospective',
      'Ask team members not to raise impediments',
      'Record impediments only in private notes',
    ],
    answer: [0, 1],
    explanation: 'Visibility and regular reassessment keep impediments from aging and quietly hurting delivery.',
  },
  {
    id: 'be4-07', domain: 'business', task: 4, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A critical piece of equipment breaks. No risk response was planned. What should the project manager do?',
    options: [
      'Apply a workaround to deal with the issue, then analyze why it wasn\'t identified',
      'Wait for a change request',
      'Add it to the risk register as a new risk only',
      'Use the contingency reserve without analysis',
    ],
    answer: 0,
    explanation: 'Workarounds are unplanned responses to issues. Then update the risk processes so similar events are anticipated next time.',
  },
  {
    id: 'be4-08', domain: 'business', task: 4, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'Which document is used to track issues, their owners, and resolution dates?',
    options: ['Issue log', 'Risk register', 'Change log', 'Assumption log'],
    answer: 0,
    explanation: 'The issue log records issues, priority, owner, due date, and status through resolution.',
  },

  // ── Task 5: Risk ─────────────────────────────────────────────────
  {
    id: 'be5-01', domain: 'business', task: 5, approach: 'predictive', difficulty: 1, type: 'match',
    stem: 'Match each negative risk response to an example.',
    left: ['Avoid', 'Transfer', 'Mitigate', 'Accept'],
    right: [
      'Change the plan to remove the threat',
      'Buy insurance or use a fixed-price contract',
      'Add extra testing to reduce probability',
      'Set aside contingency and do nothing else',
    ],
    explanation: 'Threat strategies: escalate, avoid, transfer, mitigate, accept.',
  },
  {
    id: 'be5-02', domain: 'business', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A risk has a 30% probability and an impact of $50,000. Another has a 10% probability and an impact of $120,000. What is their combined expected monetary value (EMV)?',
    options: ['−$27,000', '−$17,000', '−$170,000', '−$12,000'],
    answer: 0,
    explanation: 'EMV = 0.3 × −50,000 + 0.1 × −120,000 = −15,000 + −12,000 = −$27,000.',
  },
  {
    id: 'be5-03', domain: 'business', task: 5, approach: 'hybrid', difficulty: 2, type: 'hotspot',
    stem: 'Tap the risk that should receive the HIGHEST priority for response planning.',
    graphic: {
      kind: 'riskMatrix', title: 'Probability × Impact',
      risks: [
        { id: 'r1', label: 'Vendor delay', p: 2, i: 4 },
        { id: 'r2', label: 'Data breach', p: 4, i: 5 },
        { id: 'r3', label: 'Staff turnover', p: 3, i: 2 },
        { id: 'r4', label: 'Weather', p: 5, i: 1 },
      ],
    },
    answer: 'r2',
    explanation: 'Data breach has high probability (4) and very high impact (5), the highest P×I score (20), so it gets priority.',
  },
  {
    id: 'be5-04', domain: 'business', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A positive risk (opportunity) could reduce costs if a new supplier joins the market. The project manager partners with another company to improve the chance of capturing it. This response is:',
    options: ['Share', 'Exploit', 'Enhance', 'Accept'],
    answer: 0,
    explanation: 'Sharing means allocating ownership to a third party (e.g., a partnership) best able to capture the opportunity.',
  },
  {
    id: 'be5-05', domain: 'business', task: 5, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'How are risks typically managed on an agile project?',
    options: [
      'Only at the start through a large risk workshop',
      'Continuously: risk-based spikes, short iterations, frequent reviews, and risk items prioritized in the backlog',
      'Agile projects have no risks',
      'Risks are handled only by the sponsor',
    ],
    answer: 1,
    explanation: 'Agile reduces risk through short feedback loops and treats risk responses as backlog work (e.g., spikes), reviewed often.',
  },
  {
    id: 'be5-06', domain: 'business', task: 5, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A threat is outside the project manager\'s authority and affects the wider program. What is the appropriate response strategy?',
    options: ['Escalate', 'Avoid', 'Accept', 'Mitigate'],
    answer: 0,
    explanation: 'Escalate is used when a threat is outside the project scope or the project manager\'s authority. The owner at the program or portfolio level then manages it.',
  },
  {
    id: 'be5-07', domain: 'business', task: 5, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'What is a risk trigger?',
    options: [
      'A warning sign that a risk is about to occur or has occurred',
      'The response plan',
      'The risk owner',
      'A contingency reserve',
    ],
    answer: 0,
    explanation: 'Triggers are early warning signs that tell the risk owner to act on the response plan.',
  },
  {
    id: 'be5-08', domain: 'business', task: 5, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'After mitigating a major security risk, a smaller risk remains, and the mitigation itself introduces a new dependency on a third-party tool. These are called:',
    options: [
      'Residual risk and secondary risk',
      'Secondary risk and residual risk',
      'Known-unknowns',
      'Triggers',
    ],
    answer: 0,
    explanation: 'Residual risk remains after a response. Secondary risk arises as a direct result of implementing a response.',
  },
  {
    id: 'be5-09', domain: 'business', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Which tool is used to show the probability distribution of possible project completion dates?',
    options: ['Monte Carlo simulation', 'RACI matrix', 'Pareto chart', 'Stakeholder cube'],
    answer: 0,
    explanation: 'Monte Carlo simulation runs many scenarios to produce a probability distribution of outcomes, e.g., "80% confidence of finishing by June 30".',
  },

  // ── Task 6: Continuous improvement ───────────────────────────────
  {
    id: 'be6-01', domain: 'business', task: 6, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which agile event is specifically designed for continuous process improvement?',
    options: ['Retrospective', 'Sprint review', 'Daily standup', 'Backlog refinement'],
    answer: 0,
    explanation: 'The retrospective is for the team to inspect how it works and plan improvements.',
  },
  {
    id: 'be6-02', domain: 'business', task: 6, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'The team identifies the same improvement ideas in every retrospective, but nothing changes. What should the project manager do?',
    options: [
      'Stop holding retrospectives',
      'Help the team pick one or two improvements, assign owners, add them to the backlog, and review progress next time',
      'Ask management to impose changes',
      'Record the ideas in a document and file it',
    ],
    answer: 1,
    explanation: 'Improvement needs commitment and follow-through. Make actions small, owned, visible, and reviewed.',
  },
  {
    id: 'be6-03', domain: 'business', task: 6, approach: 'predictive', difficulty: 2, type: 'match',
    stem: 'Match each PDCA step to its activity.',
    left: ['Plan', 'Do', 'Check', 'Act'],
    right: [
      'Identify improvement and design the change',
      'Implement the change on a small scale',
      'Measure and compare results to expectations',
      'Standardize the change or adjust and repeat',
    ],
    explanation: 'The Deming (Shewhart) cycle is the foundation of continuous improvement.',
  },
  {
    id: 'be6-04', domain: 'business', task: 6, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A project discovers a better estimating technique that other projects could use. What should the project manager do?',
    options: [
      'Keep it within the project',
      'Update the organizational process assets (e.g., templates, guidelines) through the PMO',
      'Patent it',
      'Wait for another project to discover it',
    ],
    answer: 1,
    explanation: 'Updating OPAs spreads improvements across the organization. The ECO lists this explicitly.',
  },
  {
    id: 'be6-05', domain: 'business', task: 6, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'Cycle time has increased steadily for three sprints. What is the BEST way to drive improvement?',
    options: [
      'Ask the team to work faster',
      'Use the data in a retrospective to identify root causes, e.g., with a value stream map, and run an improvement experiment',
      'Increase WIP limits',
      'Stop measuring cycle time',
    ],
    answer: 1,
    explanation: 'Data-driven improvement: find the root cause (e.g., waiting time in the value stream), then test a targeted change.',
  },
  {
    id: 'be6-06', domain: 'business', task: 6, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Kaizen refers to:',
    options: ['Continuous small, incremental improvements', 'A single large transformation', 'A risk response', 'A contract type'],
    answer: 0,
    explanation: 'Kaizen is the philosophy of ongoing, incremental improvement involving everyone.',
  },
  {
    id: 'be6-07', domain: 'business', task: 6, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'An organization\'s project templates have not been updated in five years and teams ignore them. What should the project manager recommend?',
    options: [
      'Enforce use of the old templates',
      'Collect feedback and lessons learned to update the templates with the PMO, and set a regular review cycle',
      'Let every team create its own',
      'Remove all templates',
    ],
    answer: 1,
    explanation: 'Continuous improvement processes themselves must be kept current. A periodic review makes OPAs stay relevant.',
  },
  {
    id: 'be6-08', domain: 'business', task: 6, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'Which retrospective format helps the team explore what to start, stop, and continue doing?',
    options: ['Start/Stop/Continue', 'Planning poker', 'MoSCoW', 'Monte Carlo'],
    answer: 0,
    explanation: 'Start/Stop/Continue is a simple retrospective format focused on actionable improvements.',
  },

  // ── Task 7: Organizational change ────────────────────────────────
  {
    id: 'be7-01', domain: 'business', task: 7, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'A new ERP system will change how 500 employees work. Besides delivering the system, what should the project plan include?',
    options: [
      'Organizational change management: communication, training, and support for adoption',
      'Nothing; users will adapt',
      'Only technical documentation',
      'A penalty for non-users',
    ],
    answer: 0,
    explanation: 'Benefits come from adoption. Change management activities help people move from the current state to the future state.',
  },
  {
    id: 'be7-02', domain: 'business', task: 7, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Before introducing agile practices into a traditional, hierarchical organization, what should the project manager do FIRST?',
    options: [
      'Mandate agile ceremonies immediately',
      'Assess the organizational culture and readiness for change',
      'Replace all managers',
      'Start with a large-scale framework',
    ],
    answer: 1,
    explanation: 'Assessing culture comes first. It shows what will help or block the change and shapes the approach (e.g., a pilot).',
  },
  {
    id: 'be7-03', domain: 'business', task: 7, approach: 'hybrid', difficulty: 2, type: 'dropdown',
    stem: 'Complete the ADKAR model.',
    text: 'ADKAR stands for Awareness, {0}, Knowledge, {1}, and Reinforcement.',
    blanks: [
      { options: ['Desire', 'Delivery', 'Decision'], answer: 0 },
      { options: ['Ability', 'Acceptance', 'Authority'], answer: 0 },
    ],
    explanation: 'ADKAR (Prosci): Awareness of the need, Desire to support, Knowledge of how, Ability to do it, Reinforcement to sustain it.',
  },
  {
    id: 'be7-04', domain: 'business', task: 7, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'Users are resisting a new tool the project delivered. What is the BEST response?',
    options: [
      'Force adoption with management orders',
      'Engage users to understand their concerns, involve champions, and adjust training or the product based on feedback',
      'Revert to the old tool',
      'Ignore resistance; it will pass',
    ],
    answer: 1,
    explanation: 'Resistance often signals real concerns. Engaging users, using change champions, and adapting increases adoption.',
  },
  {
    id: 'be7-05', domain: 'business', task: 7, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A company merger is announced mid-project, creating uncertainty about reporting lines and priorities. What should the project manager do?',
    options: [
      'Continue as if nothing happened',
      'Evaluate the impact of the change on the project, communicate openly with the team, and confirm priorities with the sponsor',
      'Pause the project indefinitely',
      'Resign',
    ],
    answer: 1,
    explanation: 'Evaluate the impact of organizational change on the project and determine required actions, while keeping the team informed.',
  },
  {
    id: 'be7-06', domain: 'business', task: 7, approach: 'predictive', difficulty: 2, type: 'multi',
    stem: 'Which TWO factors are part of organizational culture that a project manager should assess?',
    options: ['Tolerance for risk', 'Decision-making style (hierarchical vs. collaborative)', 'Current exchange rate', 'Weather patterns', 'Market interest rates'],
    answer: [0, 1],
    explanation: 'Culture includes values, risk tolerance, decision-making style, and attitudes toward change. Exchange rates and weather are external factors.',
  },
  {
    id: 'be7-07', domain: 'business', task: 7, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What is the role of a "change champion" in organizational change?',
    options: [
      'An influential member of the affected group who promotes and supports the change',
      'The person who approves change requests',
      'An external auditor',
      'The person who writes the code',
    ],
    answer: 0,
    explanation: 'Champions are trusted peers who model the new way of working and help others adopt it.',
  },
  {
    id: 'be7-08', domain: 'business', task: 7, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'The project will automate tasks currently done by a team, and employees fear job loss. What is the MOST appropriate action?',
    options: [
      'Keep the automation secret until launch',
      'Work with HR and leadership on transparent communication about impact, reskilling, and support',
      'Tell them their jobs are safe without confirming',
      'Avoid the topic',
    ],
    answer: 1,
    explanation: 'Honest, coordinated communication and support (e.g., reskilling) address people impacts ethically and reduce resistance.',
  },

  // ── Task 8: External business environment ───────────────────────
  {
    id: 'be8-01', domain: 'business', task: 8, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'Which is an example of an external business environment change?',
    options: ['A new government tariff on imported components', 'A team member going on vacation', 'An internal template update', 'A sprint retrospective'],
    answer: 0,
    explanation: 'External changes include regulations, technology, geopolitics, and market conditions.',
  },
  {
    id: 'be8-02', domain: 'business', task: 8, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'A competitor launches a feature that makes part of your planned roadmap obsolete. What should the product owner and project manager do?',
    options: [
      'Continue building the roadmap as planned',
      'Assess the impact and re-prioritize the backlog based on the new market reality',
      'Copy the competitor\'s feature exactly',
      'Cancel the product',
    ],
    answer: 1,
    explanation: 'Assess and prioritize the impact of external changes on scope/backlog. Agile backlogs make this re-prioritization cheap.',
  },
  {
    id: 'be8-03', domain: 'business', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Which analysis technique helps a project manager survey political, economic, social, technological, legal, and environmental factors?',
    options: ['PESTLE analysis', 'Pareto analysis', 'Earned value analysis', 'Critical path analysis'],
    answer: 0,
    explanation: 'PESTLE structures the scan of external environment factors that may affect the project.',
  },
  {
    id: 'be8-04', domain: 'business', task: 8, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Geopolitical tension threatens a key offshore vendor\'s ability to deliver. The project is in execution. What is the BEST action?',
    options: [
      'Wait and see what happens',
      'Assess impact, update the risk register, and develop contingency options such as alternative vendors with stakeholders',
      'Immediately terminate the vendor contract',
      'Ignore it since it is outside the project\'s control',
    ],
    answer: 1,
    explanation: 'External threats need analysis and proactive response planning even when they cannot be controlled.',
  },
  {
    id: 'be8-05', domain: 'business', task: 8, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'How should a team keep reviewing the external environment for impacts on the backlog?',
    options: [
      'Once at project start',
      'Regularly, e.g., in backlog refinement and roadmap reviews, with input from market and regulatory stakeholders',
      'Only when a stakeholder complains',
      'Never; it\'s the sponsor\'s job',
    ],
    answer: 1,
    explanation: 'The ECO asks the PM to continually review the external environment. Building it into regular events keeps the backlog relevant.',
  },
  {
    id: 'be8-06', domain: 'business', task: 8, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A new, more efficient technology becomes available mid-project. Adopting it would require rework but would cut long-term operating costs by 40%. What should the project manager do?',
    options: [
      'Adopt it immediately',
      'Analyze the cost-benefit and impact, then submit a recommendation through change control',
      'Ignore it until the next project',
      'Let the team decide informally',
    ],
    answer: 1,
    explanation: 'External technology changes are assessed for value and impact, and decisions go through governance and change control.',
  },
  {
    id: 'be8-07', domain: 'business', task: 8, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Enterprise environmental factors (EEFs) are:',
    options: [
      'Conditions not under the project team\'s control that influence the project',
      'Templates owned by the PMO',
      'The project\'s risk responses',
      'The team\'s working agreements',
    ],
    answer: 0,
    explanation: 'EEFs (internal or external) constrain or influence the project but are not under the team\'s control, e.g., regulations, market conditions, culture.',
  },
  {
    id: 'be8-08', domain: 'business', task: 8, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Inflation has raised material costs by 12% since the budget was approved. The contract with the client is fixed-price. What should the project manager do?',
    options: [
      'Absorb the cost silently',
      'Quantify the impact, review reserves and contract terms (e.g., escalation clauses), and inform the sponsor with options',
      'Reduce quality to compensate',
      'Invoice the client for the difference',
    ],
    answer: 1,
    explanation: 'Market changes need impact assessment, use of reserves and contract provisions, and transparent communication. Quietly cutting quality is unethical.',
  },
];
