import type { Question } from '../types';

export const PEOPLE: Question[] = [
  // ── Task 1: Develop a common vision ──────────────────────────────
  {
    id: 'pe1-01', domain: 'people', task: 1, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'A newly formed agile team keeps debating which features matter most because members describe the product goal differently. What should the project manager do first?',
    options: [
      'Facilitate a session with the product owner and team to co-create a product vision statement',
      'Ask the sponsor to send an email describing the goal',
      'Let the team self-organize and resolve it during the next retrospective',
      'Lock the backlog until the disagreement goes away',
    ],
    answer: 0,
    explanation: 'A shared vision is built collaboratively. Co-creating a vision statement (e.g., an elevator pitch or product box) aligns the team now. Waiting for a retrospective delays alignment, and a one-way email does not create shared understanding.',
  },
  {
    id: 'pe1-02', domain: 'people', task: 1, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Six months into a hybrid program, a market shift changes the business goal. Several team members are still building toward the original objective. What is the BEST action?',
    options: [
      'Continue with the current plan since the baseline was approved',
      'Update the vision with key stakeholders, then communicate the refreshed vision and its impact to the team',
      'Escalate to the PMO and wait for a new charter',
      'Ask each team lead to reinterpret the goal for their own workstream',
    ],
    answer: 1,
    explanation: 'The ECO asks the project manager to keep the vision current and promote it. Refresh it with key stakeholders, then communicate it. Letting each lead reinterpret it fragments the vision.',
  },
  {
    id: 'pe1-03', domain: 'people', task: 1, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'During sprint review, a stakeholder says the increment "is not what we meant at all." The team built exactly what the stories described. What should the project manager do to address the root cause?',
    options: [
      'Have the team rebuild the increment over the weekend',
      'Add more detailed acceptance criteria to every story going forward',
      'Break down the misunderstanding with the stakeholder and product owner to find where the shared vision diverged',
      'Record a defect and move on to the next sprint',
    ],
    answer: 2,
    explanation: 'The ECO calls for breaking down situations to find the root cause of a misunderstanding of the vision. More detailed criteria may help later, but first find where understanding diverged.',
  },
  {
    id: 'pe1-04', domain: 'people', task: 1, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which document most directly communicates the high-level purpose, objectives, and success criteria of a predictive project to align stakeholders at the start?',
    options: ['Project charter', 'Risk register', 'Work breakdown structure', 'Issue log'],
    answer: 0,
    explanation: 'The charter formally authorizes the project and records its purpose, measurable objectives, and high-level success criteria, which makes it the foundation of a common vision.',
  },
  {
    id: 'pe1-05', domain: 'people', task: 1, approach: 'agile', difficulty: 2, type: 'multi',
    stem: 'Which TWO techniques help an agile team build and keep a shared product vision?',
    options: ['Product vision board', 'Gantt chart baseline', 'Sprint goal set at each planning', 'Earned value report', 'Procurement statement of work'],
    answer: [0, 2],
    explanation: 'A product vision board captures the overall vision, and sprint goals tie each iteration back to it. Gantt baselines, EVM reports, and SOWs serve other purposes.',
  },
  {
    id: 'pe1-06', domain: 'people', task: 1, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A distributed team in three countries reports low engagement. A survey shows people cannot explain how their work contributes to the organization\'s strategy. What should the project manager do?',
    options: [
      'Increase the frequency of status reports',
      'Link the project objectives to strategic goals in a visual roadmap and review it regularly with each location',
      'Replace remote team members with co-located staff',
      'Ask HR to run a motivation workshop',
    ],
    answer: 1,
    explanation: 'People engage when they can see how their work connects to strategy. A roadmap that shows the link, revisited regularly, promotes and maintains the shared vision across locations.',
  },
  {
    id: 'pe1-07', domain: 'people', task: 1, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'Two senior stakeholders sign the charter but later reveal very different expectations of what "success" means. What should the project manager have done to prevent this?',
    options: [
      'Required both stakeholders to sign a non-disclosure agreement',
      'Defined measurable success criteria and confirmed each stakeholder\'s understanding before approval',
      'Kept the charter vague to give the team flexibility',
      'Let the sponsor decide later which interpretation is correct',
    ],
    answer: 1,
    explanation: 'Measurable success criteria, validated with each key stakeholder, turn a vague goal into a shared vision. A signature alone does not guarantee shared understanding.',
  },
  {
    id: 'pe1-08', domain: 'people', task: 1, approach: 'agile', difficulty: 1, type: 'match',
    stem: 'Match each artifact to its role in creating a common vision.',
    left: ['Product vision statement', 'Product roadmap', 'Sprint goal', 'Definition of Done'],
    right: [
      'Long-term "why" and target outcome',
      'Sequence of value delivery over time',
      'Short-term objective for one iteration',
      'Shared quality standard for increments',
    ],
    explanation: 'The vision gives the why, the roadmap the path, the sprint goal the near-term focus, and the Definition of Done a shared quality bar.',
  },

  // ── Task 2: Manage conflicts ─────────────────────────────────────
  {
    id: 'pe2-01', domain: 'people', task: 2, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'Two developers argue loudly about which framework to use. The decision is important and both have valid technical points. Which conflict-resolution approach generally gives the most lasting result?',
    options: ['Smoothing/accommodating', 'Forcing/directing', 'Collaborating/problem solving', 'Withdrawing/avoiding'],
    answer: 2,
    explanation: 'Collaborating brings in multiple viewpoints to reach consensus and commitment, which makes it the most lasting win-win approach when time allows and the issue matters.',
  },
  {
    id: 'pe2-02', domain: 'people', task: 2, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A safety-critical decision must be made in the next hour. Two engineers disagree and further discussion is going in circles. What approach is MOST appropriate?',
    options: ['Collaborate until consensus is reached', 'Force/direct a decision', 'Withdraw and revisit next week', 'Smooth over the differences'],
    answer: 1,
    explanation: 'Forcing is usually a last resort, but it fits when an urgent, safety-critical decision is needed and collaboration has failed.',
  },
  {
    id: 'pe2-03', domain: 'people', task: 2, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'A team member repeatedly interrupts others during daily standups, breaking the team\'s working agreement. Others are becoming frustrated. What should the project manager do FIRST?',
    options: [
      'Report the behavior to the functional manager',
      'Remove the person from the standup',
      'Speak privately with the team member about the working agreement and its impact',
      'Ignore it; agile teams self-organize',
    ],
    answer: 2,
    explanation: 'Managing ground rule violations starts with a private, respectful conversation. Escalating first or ignoring it lets the conflict grow.',
  },
  {
    id: 'pe2-04', domain: 'people', task: 2, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Conflict between the QA lead and the development lead has continued for weeks. Before choosing a resolution technique, what should the project manager do?',
    options: [
      'Pick the technique the project manager is most comfortable with',
      'Analyze the context: the source, intensity, importance, and relationships involved',
      'Ask the sponsor to choose a technique',
      'Move one of the leads to another project',
    ],
    answer: 1,
    explanation: 'The ECO lists identifying the conflict source and analyzing its context before implementing a resolution. The right technique depends on importance, urgency, relationships, and power.',
  },
  {
    id: 'pe2-05', domain: 'people', task: 2, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What is the PRIMARY purpose of a team charter or working agreement in relation to conflict?',
    options: [
      'To define project budget authority',
      'To establish agreed ground rules that reduce and help resolve conflict',
      'To list the project\'s deliverables',
      'To document the contract terms with vendors',
    ],
    answer: 1,
    explanation: 'Team charters and working agreements set ground rules for behavior, communication, and decision-making. That prevents many conflicts and gives a reference point when they occur.',
  },
  {
    id: 'pe2-06', domain: 'people', task: 2, approach: 'predictive', difficulty: 2, type: 'match',
    stem: 'Match each conflict-resolution technique to its description.',
    left: ['Compromise/reconcile', 'Smooth/accommodate', 'Withdraw/avoid', 'Collaborate/problem solve'],
    right: [
      'Each party gives up something to reach a partial win',
      'Emphasizes areas of agreement over differences',
      'Retreats from or postpones the conflict',
      'Combines viewpoints to reach consensus and commitment',
    ],
    explanation: 'These are the five classic techniques (with force/direct). Compromise is lose-lose to a degree, smoothing preserves harmony, withdrawing postpones, collaborating is win-win.',
  },
  {
    id: 'pe2-07', domain: 'people', task: 2, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A vendor\'s team and the internal team blame each other for integration defects, and tension is visible in meetings. The contract is fixed-price. What is the BEST next step?',
    options: [
      'Issue a formal notice of breach to the vendor',
      'Facilitate a joint root-cause session focused on the integration process, not on people',
      'Tell the internal team to fix all defects to keep the peace',
      'Stop joint meetings until defects are resolved',
    ],
    answer: 1,
    explanation: 'Moving from blame to a shared, process-focused problem keeps both teams collaborating. Legal steps come only after collaboration fails and if the contract has been breached.',
  },
  {
    id: 'pe2-08', domain: 'people', task: 2, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'In a retrospective, team members disagree strongly about whether to keep pair programming. The disagreement is respectful and focused on outcomes. How should the project manager view this?',
    options: [
      'As a risk that must be shut down immediately',
      'As healthy conflict that can lead to better decisions if well facilitated',
      'As a sign the team should be restructured',
      'As something to escalate to management',
    ],
    answer: 1,
    explanation: 'Not all conflict is bad. Respectful, task-focused conflict can improve decisions. The project manager facilitates it rather than suppressing it.',
  },

  // ── Task 3: Lead the project team ────────────────────────────────
  {
    id: 'pe3-01', domain: 'people', task: 3, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which leadership style is MOST associated with agile project environments?',
    options: ['Autocratic', 'Servant leadership', 'Transactional', 'Laissez-faire'],
    answer: 1,
    explanation: 'Servant leaders focus on removing obstacles, supporting the team, and enabling self-organization, which is central to agile ways of working.',
  },
  {
    id: 'pe3-02', domain: 'people', task: 3, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A highly experienced, self-directed team is working on a novel problem. Which leadership approach will MOST likely give the best results?',
    options: [
      'Directive: assign each task and check daily',
      'Delegating/empowering: set outcomes and let the team decide how',
      'Coercive: link task completion to penalties',
      'Transactional: reward only individual output',
    ],
    answer: 1,
    explanation: 'Situational leadership matches style to team maturity. A competent, committed team does best when empowered to decide how to reach the outcomes.',
  },
  {
    id: 'pe3-03', domain: 'people', task: 3, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A new team member is unsure about their responsibilities and keeps duplicating work done by others. What should the project manager do?',
    options: [
      'Review the RACI/responsibility assignment matrix with the team and clarify roles',
      'Ask the team member to work it out on their own',
      'Reduce the team member\'s workload to zero for a week',
      'Escalate to the functional manager',
    ],
    answer: 0,
    explanation: 'Establishing clear roles and responsibilities is a core leadership enabler. A RACI makes accountability explicit and stops duplicated effort.',
  },
  {
    id: 'pe3-04', domain: 'people', task: 3, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'The team asks the project manager to decide how to split a large user story. What should the project manager do?',
    options: [
      'Split the story and assign the pieces',
      'Coach the team through story-splitting techniques so they can decide',
      'Ask the sponsor to decide',
      'Defer the story to a later release',
    ],
    answer: 1,
    explanation: 'Empowering the team means building their capability rather than taking over decisions they can own. Coaching helps them become self-sufficient.',
  },
  {
    id: 'pe3-05', domain: 'people', task: 3, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Senior management asks the team to accept a 30% scope increase without moving the deadline. The team believes it is not feasible. What should the project manager do?',
    options: [
      'Accept the request to maintain management support',
      'Represent the team\'s analysis to management, showing the trade-offs and options',
      'Tell the team to work overtime until the scope is done',
      'Ignore the request and continue',
    ],
    answer: 1,
    explanation: 'Leaders represent the voice of the team. Presenting data-backed trade-offs (scope, schedule, resources) lets management make an informed decision without burning out the team.',
  },
  {
    id: 'pe3-06', domain: 'people', task: 3, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which Tuckman stage is MOST likely when team members start to challenge each other\'s ideas and roles?',
    options: ['Forming', 'Storming', 'Norming', 'Performing'],
    answer: 1,
    explanation: 'Storming is when friction appears as people assert opinions and roles. Leaders help by facilitating conflict and clarifying working agreements.',
  },
  {
    id: 'pe3-07', domain: 'people', task: 3, approach: 'hybrid', difficulty: 2, type: 'multi',
    stem: 'A team includes members from very different cultural and professional backgrounds. Which TWO actions BEST support these varied perspectives?',
    options: [
      'Establish inclusive working agreements, e.g., on turn-taking and time zones',
      'Require everyone to follow the communication style of the majority',
      'Rotate meeting times to share time-zone inconvenience',
      'Limit decisions to the most senior members',
      'Avoid discussing differences to prevent conflict',
    ],
    answer: [0, 2],
    explanation: 'Inclusive agreements and fair arrangements (like rotating meeting times) show respect and help diverse voices contribute. Forcing conformity or silencing differences reduces engagement.',
  },
  {
    id: 'pe3-08', domain: 'people', task: 3, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'A team member who was a top performer has missed several commitments and seems withdrawn. What should the project manager do FIRST?',
    options: [
      'Begin a formal performance improvement plan',
      'Have a private, supportive conversation to understand what is happening',
      'Redistribute their work without telling them',
      'Raise it in the daily standup',
    ],
    answer: 1,
    explanation: 'Emotional intelligence and servant leadership mean understanding the person first. A sudden change often has a cause the leader can help with, so formal action is premature.',
  },
  {
    id: 'pe3-09', domain: 'people', task: 3, approach: 'agile', difficulty: 2, type: 'dropdown',
    stem: 'Complete the statement about team motivation.',
    text: 'According to Herzberg, salary and working conditions are {0} factors, while recognition and growth are {1} factors.',
    blanks: [
      { options: ['hygiene', 'motivating', 'expectancy'], answer: 0 },
      { options: ['hygiene', 'motivating', 'compliance'], answer: 1 },
    ],
    explanation: 'Herzberg: hygiene factors prevent dissatisfaction but do not motivate. Motivators (achievement, recognition, growth) drive satisfaction and performance.',
  },

  // ── Task 4: Engage stakeholders ──────────────────────────────────
  {
    id: 'pe4-01', domain: 'people', task: 4, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'When should stakeholder identification begin?',
    options: [
      'After the project management plan is approved',
      'As early as possible and continue throughout the project',
      'Only during project closing',
      'When the first issue is raised',
    ],
    answer: 1,
    explanation: 'Stakeholders should be identified as early as possible (often with the charter) and reassessed throughout, because new stakeholders appear and existing ones change.',
  },
  {
    id: 'pe4-02', domain: 'people', task: 4, approach: 'hybrid', difficulty: 2, type: 'hotspot',
    stem: 'The regional regulator has HIGH power over approval but LOW interest in day-to-day project details. Tap the quadrant that shows how to engage them.',
    graphic: {
      kind: 'powerInterest',
      title: 'Power/Interest grid',
      items: [
        { id: 'sp', label: 'Sponsor', power: 0.85, interest: 0.85 },
        { id: 'eu', label: 'End users', power: 0.25, interest: 0.8 },
        { id: 'pub', label: 'Public', power: 0.2, interest: 0.2 },
      ],
    },
    answer: 'satisfy',
    explanation: 'High power, low interest → Keep Satisfied. Give them enough information to stay comfortable and consult them on matters within their authority, without overloading them.',
  },
  {
    id: 'pe4-03', domain: 'people', task: 4, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A stakeholder engagement assessment matrix shows a key department head as "Resistant" now and "Supportive" as the desired state. What should the project manager do?',
    options: [
      'Remove the department head from the stakeholder register',
      'Plan targeted engagement actions to understand concerns and move them toward supportive',
      'Escalate to the sponsor to force support',
      'Wait until the department head becomes neutral on their own',
    ],
    answer: 1,
    explanation: 'The engagement matrix shows gaps between current (C) and desired (D) engagement. The project manager plans actions to close them, starting with understanding the resistance.',
  },
  {
    id: 'pe4-04', domain: 'people', task: 4, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'An influential customer rarely attends sprint reviews, and the product is drifting from what they need. What is the BEST approach?',
    options: [
      'Proceed without the customer\'s input',
      'Find out why they are not attending and tailor engagement, such as shorter targeted demos or async video reviews',
      'Ask the product owner to guess their needs',
      'Stop sprint reviews until they can attend',
    ],
    answer: 1,
    explanation: 'Tailoring communication to stakeholder needs is an explicit ECO enabler. Understanding why they are absent and adapting the format keeps them engaged and the feedback loop alive.',
  },
  {
    id: 'pe4-05', domain: 'people', task: 4, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Midway through a project, a reorganization creates a new VP with authority over your main deliverable. The VP is not in the stakeholder register. What should the project manager do FIRST?',
    options: [
      'Continue as planned; the register was approved at kickoff',
      'Update the stakeholder register, analyze the VP\'s interests and influence, and adjust the engagement plan',
      'Send the VP the full project management plan',
      'Ask the sponsor to keep the VP out of the project',
    ],
    answer: 1,
    explanation: 'Identifying and analyzing stakeholders is continuous. A new high-influence stakeholder means updating the register and engagement approach before acting.',
  },
  {
    id: 'pe4-06', domain: 'people', task: 4, approach: 'predictive', difficulty: 1, type: 'multi',
    stem: 'Which TWO documents are the PRIMARY outputs of identifying stakeholders?',
    options: ['Stakeholder register', 'Risk breakdown structure', 'Change requests / updates to plans', 'Procurement SOW', 'Burndown chart'],
    answer: [0, 2],
    explanation: 'Identify Stakeholders mainly produces the stakeholder register, along with change requests and plan/document updates. The others belong to different processes.',
  },
  {
    id: 'pe4-07', domain: 'people', task: 4, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'Two powerful stakeholders want conflicting features in the next release. The product owner is unsure how to proceed. What should the project manager recommend?',
    options: [
      'Build both features and extend the release',
      'Bring both stakeholders together with the product owner to prioritize against agreed value criteria',
      'Pick the feature from the more senior stakeholder',
      'Build neither feature to avoid upsetting anyone',
    ],
    answer: 1,
    explanation: 'Optimizing alignment means facilitating a transparent, value-based prioritization with the stakeholders. The product owner still owns the final backlog decision.',
  },
  {
    id: 'pe4-08', domain: 'people', task: 4, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Which action BEST builds trust with a skeptical stakeholder group?',
    options: [
      'Promising more scope than can be delivered',
      'Consistently delivering on commitments and sharing bad news early and honestly',
      'Limiting their access to project information',
      'Only communicating through formal reports',
    ],
    answer: 1,
    explanation: 'Trust comes from reliability and transparency. Delivering on commitments and raising issues early builds credibility and influence.',
  },

  // ── Task 5: Align stakeholder expectations ───────────────────────
  {
    id: 'pe5-01', domain: 'people', task: 5, approach: 'predictive', difficulty: 1, type: 'match',
    stem: 'Match each stakeholder classification model to what it compares.',
    left: ['Power/interest grid', 'Salience model', 'Stakeholder cube', 'Directions of influence'],
    right: [
      'Authority vs. level of concern',
      'Power, urgency, and legitimacy',
      'Multiple grid dimensions in 3D',
      'Upward, downward, outward, sideward',
    ],
    explanation: 'These are common stakeholder categorization techniques. Each groups stakeholders differently to guide engagement.',
  },
  {
    id: 'pe5-02', domain: 'people', task: 5, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Marketing expects the new app to launch with 20 features; IT expects an MVP with 5. Both groups report to the sponsor. What should the project manager do?',
    options: [
      'Plan for 20 features to satisfy marketing',
      'Facilitate a workshop with both groups to align on release scope, value, and timing',
      'Plan for 5 features since IT is building it',
      'Ask the sponsor to send a memo',
    ],
    answer: 1,
    explanation: 'Facilitating discussions to align expectations is an ECO enabler. A joint workshop brings out the trade-offs so both groups can agree on an incremental release plan.',
  },
  {
    id: 'pe5-03', domain: 'people', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'In the salience model, a stakeholder with power, legitimacy, AND urgency is classified as:',
    options: ['Dormant', 'Dependent', 'Definitive', 'Demanding'],
    answer: 2,
    explanation: 'Definitive stakeholders have all three attributes and need immediate attention.',
  },
  {
    id: 'pe5-04', domain: 'people', task: 5, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'A junior team member wants to learn how to facilitate retrospectives. What should the project manager do?',
    options: [
      'Tell them to wait until they are senior',
      'Set up a mentoring arrangement where they co-facilitate with an experienced facilitator',
      'Send them to an external course only',
      'Let them facilitate alone with no preparation',
    ],
    answer: 1,
    explanation: 'The ECO includes organizing and acting on mentoring opportunities. Co-facilitating with a mentor builds skill while keeping the ceremony effective.',
  },
  {
    id: 'pe5-05', domain: 'people', task: 5, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'At kickoff, the sponsor expects benefits within 3 months, while the operations director expects a full-year rollout. Neither knows the other\'s view. What is the MOST effective way to surface and align these expectations?',
    options: [
      'Document both views and decide later',
      'Interview each stakeholder separately, then hold a joint session to agree measurable objectives and timeline',
      'Adopt the sponsor\'s expectation since they fund the project',
      'Wait for the first status meeting to see who objects',
    ],
    answer: 1,
    explanation: 'Identify each stakeholder\'s expectations first (interviews), then align them in a facilitated discussion and record the agreed objectives.',
  },
  {
    id: 'pe5-06', domain: 'people', task: 5, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which practice gives stakeholders the MOST frequent opportunity to recalibrate their expectations on an agile project?',
    options: ['Annual steering committee', 'Iteration/sprint reviews with working increments', 'Final acceptance test', 'Change control board meeting'],
    answer: 1,
    explanation: 'Frequent reviews of working increments let stakeholders see real progress and adjust expectations continuously.',
  },
  {
    id: 'pe5-07', domain: 'people', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A stakeholder keeps sending feature requests directly to developers, bypassing the agreed process. What should the project manager do?',
    options: [
      'Ask developers to implement requests quickly to keep the stakeholder happy',
      'Meet with the stakeholder to explain the agreed process and why it protects their interests',
      'Block the stakeholder\'s email address',
      'Report the stakeholder to the sponsor immediately',
    ],
    answer: 1,
    explanation: 'Aligning expectations includes agreeing on how stakeholders interact with the project. A direct, respectful conversation comes before escalation.',
  },
  {
    id: 'pe5-08', domain: 'people', task: 5, approach: 'hybrid', difficulty: 2, type: 'dropdown',
    stem: 'Complete the statement.',
    text: 'Stakeholders with high power and high interest should be {0}, while those with low power and low interest should be {1}.',
    blanks: [
      { options: ['managed closely', 'kept informed', 'monitored'], answer: 0 },
      { options: ['managed closely', 'kept satisfied', 'monitored'], answer: 2 },
    ],
    explanation: 'Power/interest grid: High/High = Manage Closely; High power/Low interest = Keep Satisfied; Low/High = Keep Informed; Low/Low = Monitor.',
  },

  // ── Task 6: Manage stakeholder expectations ──────────────────────
  {
    id: 'pe6-01', domain: 'people', task: 6, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which metric is a direct measure of customer satisfaction?',
    options: ['Net Promoter Score (NPS)', 'Velocity', 'Cost performance index', 'Defect density'],
    answer: 0,
    explanation: 'NPS directly measures how likely customers are to recommend the product. The others measure delivery, cost, or quality performance.',
  },
  {
    id: 'pe6-02', domain: 'people', task: 6, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Post-release surveys show internal users are dissatisfied with the new workflow, even though all acceptance criteria were met. What should the project manager do?',
    options: [
      'Close the project since criteria were met',
      'Analyze the feedback with users and the product owner, then add improvements to the backlog or a follow-up phase',
      'Tell users they will get used to it',
      'Blame the business analyst for poor requirements',
    ],
    answer: 1,
    explanation: 'Monitoring internal customer satisfaction and responding as needed is part of managing expectations. Meeting acceptance criteria does not guarantee value was delivered.',
  },
  {
    id: 'pe6-03', domain: 'people', task: 6, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A key external customer learns from a third party that the delivery will be late. They are upset. What should the project manager have done?',
    options: [
      'Hidden the delay until a recovery plan was ready',
      'Proactively communicated the delay, its cause, and the recovery options as soon as it was known',
      'Asked the third party not to share information',
      'Waited for the customer to ask',
    ],
    answer: 1,
    explanation: 'Managing expectations means sharing bad news early and transparently, with options. Surprises damage trust far more than the delay itself.',
  },
  {
    id: 'pe6-04', domain: 'people', task: 6, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'An external client expects every backlog item to be delivered by the release date. The forecast based on velocity shows only 70% is achievable. What is the BEST approach?',
    options: [
      'Commit to 100% and ask the team to work faster',
      'Share the velocity-based forecast and work with the client to prioritize the highest-value 70%',
      'Inflate story points to make the forecast look better',
      'Remove the forecast from status reports',
    ],
    answer: 1,
    explanation: 'Transparent, data-driven forecasting combined with value-based prioritization keeps external customer expectations realistic and aligned with outcomes.',
  },
  {
    id: 'pe6-05', domain: 'people', task: 6, approach: 'hybrid', difficulty: 2, type: 'multi',
    stem: 'Which TWO are effective ways to monitor stakeholder satisfaction during a project?',
    options: [
      'Pulse surveys after key milestones',
      'Reviewing the stakeholder engagement assessment matrix regularly',
      'Measuring lines of code produced',
      'Counting the number of meetings held',
      'Tracking schedule variance only',
    ],
    answer: [0, 1],
    explanation: 'Surveys and regular engagement reviews show how stakeholders feel. Output and meeting counts say nothing about satisfaction.',
  },
  {
    id: 'pe6-06', domain: 'people', task: 6, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Where would a project manager record a stakeholder\'s concern that needs follow-up and resolution?',
    options: ['Issue log', 'Lessons learned register', 'Scope baseline', 'Resource calendar'],
    answer: 0,
    explanation: 'The issue log tracks current problems and concerns, with owners and due dates, until they are resolved.',
  },
  {
    id: 'pe6-07', domain: 'people', task: 6, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'The internal customer (the operations team) and the external customer (end consumers) want different things from a release. Who should balance these needs in the backlog?',
    options: ['The development team', 'The product owner, with input from both', 'The project sponsor alone', 'The QA lead'],
    answer: 1,
    explanation: 'The product owner maximizes value by balancing internal and external stakeholder needs in backlog ordering, informed by both groups.',
  },
  {
    id: 'pe6-08', domain: 'people', task: 6, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Customer satisfaction scores dropped sharply after the last release. The cause is unknown. What should the project manager do FIRST?',
    options: [
      'Roll back the release immediately',
      'Analyze the feedback data and talk to a sample of customers to understand the drop',
      'Offer all customers a discount',
      'Fire the release manager',
    ],
    answer: 1,
    explanation: 'Understand before acting. Analyzing feedback and talking to customers shows the real cause, so the response addresses it.',
  },

  // ── Task 7: Help ensure knowledge transfer ───────────────────────
  {
    id: 'pe7-01', domain: 'people', task: 7, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'A senior architect who holds critical system knowledge is leaving in two weeks. What should the project manager do FIRST?',
    options: [
      'Ask HR to delay the departure',
      'Identify the critical knowledge and arrange structured handover sessions with the right people',
      'Ask the architect to write everything down on their last day',
      'Hire a replacement and let them learn by themselves',
    ],
    answer: 1,
    explanation: 'Identify the knowledge that is critical to the project, then gather and transfer it in a structured way while the expert is still available.',
  },
  {
    id: 'pe7-02', domain: 'people', task: 7, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'What is the difference between explicit and tacit knowledge?',
    options: [
      'Explicit knowledge is secret; tacit knowledge is public',
      'Explicit knowledge can be easily codified in words or documents; tacit knowledge is experience-based and hard to express',
      'They are the same thing',
      'Tacit knowledge is always stored in a database',
    ],
    answer: 1,
    explanation: 'Explicit knowledge can be documented (manuals, procedures). Tacit knowledge (insights, know-how) is usually shared through interaction, like mentoring, shadowing, or pairing.',
  },
  {
    id: 'pe7-03', domain: 'people', task: 7, approach: 'agile', difficulty: 2, type: 'multi',
    stem: 'Which TWO practices are MOST effective for transferring tacit knowledge within an agile team?',
    options: ['Pair programming', 'Emailing a document library link', 'Communities of practice', 'Annual performance reviews', 'Formal contracts'],
    answer: [0, 2],
    explanation: 'Tacit knowledge transfers through interaction. Pairing and communities of practice create that interaction.',
  },
  {
    id: 'pe7-04', domain: 'people', task: 7, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which project document is updated throughout the project to capture knowledge gained, and is then transferred to the organizational process assets at closing?',
    options: ['Lessons learned register', 'Requirements traceability matrix', 'Project charter', 'Procurement SOW'],
    answer: 0,
    explanation: 'The lessons learned register is created early and updated throughout. At closing it feeds the lessons learned repository (OPAs).',
  },
  {
    id: 'pe7-05', domain: 'people', task: 7, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Project documentation is extensive but team members say they cannot find what they need. What is the BEST action?',
    options: [
      'Create more documentation',
      'Ask the team how they search for information, then reorganize the knowledge base for accessibility',
      'Require team members to read all documentation weekly',
      'Delete all documentation and start over',
    ],
    answer: 1,
    explanation: 'Fostering an environment for knowledge transfer includes making knowledge accessible. Ask users first, then restructure.',
  },
  {
    id: 'pe7-06', domain: 'people', task: 7, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'The team relies on one person for all deployment tasks. If that person is absent, deployments stop. How should the project manager address this?',
    options: [
      'Accept the risk; the person is reliable',
      'Encourage cross-skilling through pairing and rotating deployment duties ("T-shaped" skills)',
      'Outsource deployments',
      'Ban deployments when the person is absent',
    ],
    answer: 1,
    explanation: 'Cross-skilling removes single points of failure and builds generalizing specialists (T-shaped team members), which agile teams value.',
  },
  {
    id: 'pe7-07', domain: 'people', task: 7, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Lessons learned are captured at the end of every project but never reused. What should the project manager do to improve this?',
    options: [
      'Stop collecting lessons learned',
      'Review relevant lessons from past projects during planning and share lessons continuously during the project',
      'Store lessons in a locked folder',
      'Only capture lessons from failed projects',
    ],
    answer: 1,
    explanation: 'Knowledge is valuable only if used. Reviewing past lessons at planning and sharing them continuously turns capture into real improvement.',
  },
  {
    id: 'pe7-08', domain: 'people', task: 7, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A project is about to hand over a complex system to the operations team. What is the BEST way to ensure knowledge transfer?',
    options: [
      'Send the operations team the final report',
      'Plan transition activities such as training, shadowing, runbooks, and a support period with acceptance criteria',
      'Have the project team remain on call indefinitely',
      'Let operations figure it out',
    ],
    answer: 1,
    explanation: 'A planned transition, combining explicit (runbooks) and tacit (shadowing, hypercare) transfer with clear acceptance criteria, ensures operations can sustain the product.',
  },

  // ── Task 8: Plan and manage communication ────────────────────────
  {
    id: 'pe8-01', domain: 'people', task: 8, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'A project team has 10 members including the project manager. How many communication channels exist?',
    options: ['45', '20', '90', '10'],
    answer: 0,
    explanation: 'Channels = n(n−1)/2 = 10 × 9 / 2 = 45.',
  },
  {
    id: 'pe8-02', domain: 'people', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A team grows from 6 to 9 people. How many communication channels are added?',
    options: ['21', '36', '15', '3'],
    answer: 0,
    explanation: '6 people: 6×5/2 = 15. 9 people: 9×8/2 = 36. Added: 36 − 15 = 21.',
  },
  {
    id: 'pe8-03', domain: 'people', task: 8, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'Which tool is an example of "osmotic communication" and visible information on an agile team?',
    options: ['Information radiator such as a Kanban board on the wall', 'Monthly email newsletter', 'Formal memo', 'Signed contract'],
    answer: 0,
    explanation: 'Information radiators make progress visible to everyone without requests, which supports transparency.',
  },
  {
    id: 'pe8-04', domain: 'people', task: 8, approach: 'hybrid', difficulty: 2, type: 'match',
    stem: 'Match each communication method to an example.',
    left: ['Interactive', 'Push', 'Pull'],
    right: ['Video call to resolve a design question', 'Weekly status email to the steering group', 'Project wiki that stakeholders browse as needed'],
    explanation: 'Interactive: real-time, multidirectional. Push: sent to specific recipients. Pull: recipients access it at their discretion.',
  },
  {
    id: 'pe8-05', domain: 'people', task: 8, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Executives complain that the 20-page status report is too long, while team leads want more detail. What should the project manager do?',
    options: [
      'Keep the report as-is for consistency',
      'Tailor reporting: a one-page dashboard for executives and detailed reports for team leads',
      'Stop sending reports',
      'Make the report longer to satisfy team leads',
    ],
    answer: 1,
    explanation: 'Reports should match each audience\'s needs. Updating the communications management plan with tailored formats serves both groups.',
  },
  {
    id: 'pe8-06', domain: 'people', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Which document defines who needs what information, when, in what format, and by which method?',
    options: ['Communications management plan', 'Stakeholder register', 'Issue log', 'Team charter'],
    answer: 0,
    explanation: 'The communications management plan sets the information needs, frequency, format, method, and responsibility for project communications.',
  },
  {
    id: 'pe8-07', domain: 'people', task: 8, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'A stakeholder says they never get feedback on the suggestions they submit, and they have stopped contributing. What should the project manager do?',
    options: [
      'Ignore it; suggestions are optional',
      'Establish a feedback loop that acknowledges each suggestion and reports what happened to it',
      'Ask the stakeholder to submit fewer suggestions',
      'Forward the suggestions to the sponsor',
    ],
    answer: 1,
    explanation: 'Closing the feedback loop is an explicit ECO enabler. Acknowledging input and reporting outcomes keeps stakeholders engaged.',
  },
  {
    id: 'pe8-08', domain: 'people', task: 8, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'The governance board requires monthly earned value reporting, but the agile teams report velocity and burnups. What should the project manager do?',
    options: [
      'Force agile teams to switch to EVM',
      'Ignore the governance requirement',
      'Create a reporting approach that translates agile metrics, e.g., release burnup and feature completion, into the information the board needs',
      'Report only to the product owner',
    ],
    answer: 2,
    explanation: 'Hybrid environments need reporting that meets governance needs without disrupting team practices. Agile metrics can be mapped to EV-style progress (agile EVM).',
  },
  {
    id: 'pe8-09', domain: 'people', task: 8, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'A message is misunderstood because the receiver was distracted. In the communication model, this distraction is called:',
    options: ['Noise', 'Encoding', 'Feedback', 'Medium'],
    answer: 0,
    explanation: 'Noise is anything that interferes with transmitting or understanding the message.',
  },
];
