import type { Question } from '../types';

export const PROCESS: Question[] = [
  // ── Task 1: Integrated plan & delivery approach ──────────────────
  {
    id: 'pr1-01', domain: 'process', task: 1, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'Requirements for a new mobile app are unclear and likely to change, but the regulatory reporting module has fixed, well-known requirements. Which development approach is MOST appropriate?',
    options: ['Pure predictive', 'Hybrid: adaptive for the app, predictive for the regulatory module', 'Pure agile with no documentation', 'Waterfall with no change control'],
    answer: 1,
    explanation: 'Tailoring the approach to each component\'s uncertainty is the core of hybrid delivery. High uncertainty suits adaptive; stable, regulated scope suits predictive.',
  },
  {
    id: 'pr1-02', domain: 'process', task: 1, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which document integrates all subsidiary management plans and baselines into a single plan?',
    options: ['Project management plan', 'Project charter', 'Business case', 'Benefits register'],
    answer: 0,
    explanation: 'The project management plan integrates the subsidiary plans (scope, schedule, cost, etc.) and the baselines.',
  },
  {
    id: 'pr1-03', domain: 'process', task: 1, approach: 'hybrid', difficulty: 2, type: 'multi',
    stem: 'Which TWO factors MOST strongly favor an adaptive (agile) development approach?',
    options: [
      'High requirements uncertainty',
      'Need for frequent customer feedback on working product',
      'Fixed, fully understood requirements',
      'Strict regulatory sign-off for every document',
      'Single big-bang delivery with no interim value',
    ],
    answer: [0, 1],
    explanation: 'Adaptive approaches suit high uncertainty and benefit from frequent feedback. Fixed requirements and document-heavy sign-off favor predictive.',
  },
  {
    id: 'pr1-04', domain: 'process', task: 1, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'While consolidating subsidiary plans, the project manager finds the resource plan assumes a specialist is available in Q2, but the schedule needs them in Q1. What should the project manager do?',
    options: [
      'Ignore it; plans are only estimates',
      'Resolve the dependency gap by adjusting the schedule or securing the resource, then update the integrated plan',
      'Approve both plans as-is',
      'Remove the specialist\'s tasks from scope',
    ],
    answer: 1,
    explanation: 'Assessing consolidated plans for dependencies and gaps is a key integration activity. Inconsistencies must be resolved before baselining.',
  },
  {
    id: 'pr1-05', domain: 'process', task: 1, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'The organization now requires carbon-impact reporting for all projects. How should the project manager handle this new information requirement?',
    options: [
      'Ignore it unless the sponsor asks',
      'Include sustainability metrics in the integrated plan and define how they will be collected and reported',
      'Handle it only at project closure',
      'Ask the team to estimate it at the end',
    ],
    answer: 1,
    explanation: 'The 2026 ECO names sustainability as a critical information requirement. Plan it in up front with collection and reporting methods.',
  },
  {
    id: 'pr1-06', domain: 'process', task: 1, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'An AI tool forecasts that the project will miss its release date with 80% probability. What should the project manager do with this information?',
    options: [
      'Publish the forecast as fact to stakeholders',
      'Ignore AI outputs entirely',
      'Validate the forecast against team data and judgment, then use it to inform decisions and discussions',
      'Change the release date automatically',
    ],
    answer: 2,
    explanation: 'Data-informed decisions mean treating AI forecasts as inputs to check with real data and expert judgment, not as automatic decisions or something to ignore.',
  },
  {
    id: 'pr1-07', domain: 'process', task: 1, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'Mid-project, the sponsor asks whether the project still makes business sense after a 25% cost increase. What should the project manager do?',
    options: [
      'Assure the sponsor that all projects overrun',
      'Reassess the business case and benefits against the new cost forecast and present options',
      'Cancel the project',
      'Hide the cost increase until closure',
    ],
    answer: 1,
    explanation: 'The ECO asks the project manager to assess plans for continued business value. Re-evaluating the business case with current data supports the governance decision.',
  },
  {
    id: 'pr1-08', domain: 'process', task: 1, approach: 'hybrid', difficulty: 2, type: 'dropdown',
    stem: 'Complete the statement about development approaches.',
    text: 'A project that delivers the full product at the end uses a {0} life cycle, while one that delivers usable pieces in successive releases uses an {1} life cycle.',
    blanks: [
      { options: ['predictive', 'iterative', 'incremental'], answer: 0 },
      { options: ['predictive', 'incremental', 'governance'], answer: 1 },
    ],
    explanation: 'Predictive delivers once at the end. Incremental delivers finished, usable increments over time. Iterative refines the product through repeated cycles.',
  },

  // ── Task 2: Develop and manage scope ─────────────────────────────
  {
    id: 'pr2-01', domain: 'process', task: 2, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which three components make up the scope baseline?',
    options: [
      'Project scope statement, WBS, and WBS dictionary',
      'Charter, requirements documentation, and WBS',
      'Scope statement, schedule, and budget',
      'Backlog, sprint plan, and burndown',
    ],
    answer: 0,
    explanation: 'The scope baseline = approved scope statement + WBS + WBS dictionary.',
  },
  {
    id: 'pr2-02', domain: 'process', task: 2, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A developer adds a "small" extra report the customer mentioned informally, without a change request. This is an example of:',
    options: ['Gold plating', 'Scope validation', 'Progressive elaboration', 'Decomposition'],
    answer: 0,
    explanation: 'Gold plating is adding features not in approved scope, which adds risk and cost. Changes should go through change control.',
  },
  {
    id: 'pr2-03', domain: 'process', task: 2, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'In agile, which artifact holds the evolving scope and is continuously refined and reprioritized?',
    options: ['Product backlog', 'Scope statement', 'WBS dictionary', 'Change log'],
    answer: 0,
    explanation: 'The product backlog is the single, ordered list of everything that might be needed. Its scope emerges through refinement.',
  },
  {
    id: 'pr2-04', domain: 'process', task: 2, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'What is the difference between Validate Scope and Control Quality?',
    options: [
      'Validate Scope checks correctness; Control Quality checks acceptance',
      'Validate Scope is formal acceptance of deliverables by the customer; Control Quality checks deliverables meet quality requirements',
      'They are the same process',
      'Control Quality is performed only after Validate Scope',
    ],
    answer: 1,
    explanation: 'Control Quality (usually first) checks correctness. Validate Scope gets formal customer/sponsor acceptance of the verified deliverables.',
  },
  {
    id: 'pr2-05', domain: 'process', task: 2, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'A user story is too large to complete in one sprint. What should the team do?',
    options: [
      'Extend the sprint',
      'Split the story into smaller vertical slices that each deliver value',
      'Split the story into front-end and back-end tasks across teams',
      'Remove the story from the backlog',
    ],
    answer: 1,
    explanation: 'Vertical slicing keeps each piece independently valuable and testable (INVEST). Horizontal splits by layer deliver no usable value on their own.',
  },
  {
    id: 'pr2-06', domain: 'process', task: 2, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'The 100% rule for a WBS means:',
    options: [
      'Every work package must be 100% complete before the next starts',
      'The WBS includes all the work, project and product, and nothing extra; child levels sum to the parent',
      'Each work package takes 100 hours',
      'The WBS must be 100% approved by all stakeholders',
    ],
    answer: 1,
    explanation: 'The 100% rule: the WBS captures all work defined by the scope (including project management), and the sum of child elements equals the parent.',
  },
  {
    id: 'pr2-07', domain: 'process', task: 2, approach: 'hybrid', difficulty: 2, type: 'match',
    stem: 'Match each scope artifact to its purpose.',
    left: ['Requirements traceability matrix', 'WBS dictionary', 'Scope statement', 'Acceptance criteria'],
    right: [
      'Links requirements to their origin and deliverables',
      'Details each WBS component (description, owner, criteria)',
      'Describes deliverables, exclusions, constraints, assumptions',
      'Conditions a deliverable must meet to be accepted',
    ],
    explanation: 'Each artifact supports defining, decomposing, and controlling scope at a different level of detail.',
  },
  {
    id: 'pr2-08', domain: 'process', task: 2, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'Stakeholders cannot agree on the MVP scope. What technique can BEST help them reach agreement quickly?',
    options: ['MoSCoW prioritization in a facilitated session', 'Monte Carlo simulation', 'Make-or-buy analysis', 'Earned value analysis'],
    answer: 0,
    explanation: 'MoSCoW (Must, Should, Could, Won\'t) gives stakeholders a shared language for agreeing what is essential to the MVP.',
  },

  // ── Task 3: Value-based delivery ─────────────────────────────────
  {
    id: 'pr3-01', domain: 'process', task: 3, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What is the PRIMARY purpose of a minimum viable product (MVP)?',
    options: [
      'To deliver the full product as cheaply as possible',
      'To test assumptions and learn from real users with the least effort',
      'To satisfy contractual requirements',
      'To avoid writing documentation',
    ],
    answer: 1,
    explanation: 'An MVP validates hypotheses with real users early, which reduces the risk of building the wrong thing.',
  },
  {
    id: 'pr3-02', domain: 'process', task: 3, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'Feature A has a value score of 40 and an effort of 8 points. Feature B has value 30 and effort 3. Feature C has value 50 and effort 20. Using WSJF-style value/effort, which should be done FIRST?',
    options: ['Feature A', 'Feature B', 'Feature C', 'All have equal priority'],
    answer: 1,
    explanation: 'Value ÷ effort: A = 5, B = 10, C = 2.5. B gives the most value per unit of effort.',
  },
  {
    id: 'pr3-03', domain: 'process', task: 3, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A project delivered all scope on time and on budget, but six months later none of the expected benefits have appeared. What was MOST likely missing?',
    options: [
      'A detailed WBS',
      'A benefits measurement system and ownership for tracking benefits realization',
      'More status meetings',
      'A larger contingency reserve',
    ],
    answer: 1,
    explanation: 'The ECO asks the PM to verify a measurement system is in place to track benefits. Without a benefits management plan and owners, outputs may not become outcomes.',
  },
  {
    id: 'pr3-04', domain: 'process', task: 3, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Which document describes the targeted benefits, the timeframe, the benefits owner, and the metrics?',
    options: ['Benefits management plan', 'Scope management plan', 'Quality management plan', 'Resource breakdown structure'],
    answer: 0,
    explanation: 'The benefits management plan (with the business case) describes how and when benefits will be delivered and measured.',
  },
  {
    id: 'pr3-05', domain: 'process', task: 3, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'Analytics show that a recently released feature is used by only 2% of users, far below the 30% hypothesis. What is the BEST response?',
    options: [
      'Keep enhancing the feature since effort was already spent',
      'Use the data to re-evaluate the feature\'s value and reprioritize the backlog, possibly pivoting',
      'Hide the analytics from stakeholders',
      'Remove analytics tracking',
    ],
    answer: 1,
    explanation: 'Examining business value throughout and adjusting based on evidence is key to value delivery. Sunk cost should not drive further investment.',
  },
  {
    id: 'pr3-06', domain: 'process', task: 3, approach: 'hybrid', difficulty: 1, type: 'multi',
    stem: 'Which TWO are ways to deliver value incrementally?',
    options: ['Release an MVP and iterate', 'Phase a rollout region by region', 'Hold all features until the final release', 'Defer all testing to the end', 'Approve every change at year end'],
    answer: [0, 1],
    explanation: 'MVPs and phased rollouts deliver usable value early and allow learning. Holding everything back delays value.',
  },
  {
    id: 'pr3-07', domain: 'process', task: 3, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'Which stakeholder is primarily accountable for maximizing the value of the product in Scrum?',
    options: ['Product owner', 'Scrum master', 'Developers', 'Sponsor'],
    answer: 0,
    explanation: 'The product owner is accountable for maximizing value, mainly through ordering the product backlog.',
  },
  {
    id: 'pr3-08', domain: 'process', task: 3, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'Project A has an NPV of $120K over 5 years. Project B has an NPV of $95K over 3 years. Funds allow only one. Based on NPV alone, which should be selected?',
    options: ['Project A', 'Project B', 'Neither; NPV must be adjusted for duration first', 'Both should be split'],
    answer: 0,
    explanation: 'NPV already accounts for the time value of money. Choose the higher NPV ($120K). Project length is already built into the NPV.',
  },

  // ── Task 4: Resources ────────────────────────────────────────────
  {
    id: 'pr4-01', domain: 'process', task: 4, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which technique adjusts start and finish dates based on resource constraints, often extending the critical path?',
    options: ['Resource leveling', 'Resource smoothing', 'Fast tracking', 'Crashing'],
    answer: 0,
    explanation: 'Resource leveling balances demand against supply and can change the critical path. Resource smoothing stays within float and does not.',
  },
  {
    id: 'pr4-02', domain: 'process', task: 4, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'In a matrix organization, a team member says their functional manager has reassigned them to another project for two weeks. What should the project manager do FIRST?',
    options: [
      'Escalate to the sponsor',
      'Assess the impact on the schedule and discuss with the functional manager',
      'Hire a contractor immediately',
      'Accept it and say nothing',
    ],
    answer: 1,
    explanation: 'First assess impact, then negotiate with the functional manager. Escalation comes only if negotiation fails.',
  },
  {
    id: 'pr4-03', domain: 'process', task: 4, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'An agile team is regularly pulled into unplanned support work, disrupting sprint commitments. What is the BEST way to manage this?',
    options: [
      'Refuse all support requests',
      'Make the support demand visible and reserve capacity for it, or set up a rotating support role',
      'Add the support to overtime',
      'Extend every sprint',
    ],
    answer: 1,
    explanation: 'Making work visible and planning capacity for it (or rotating a support duty) protects predictability while meeting operational needs.',
  },
  {
    id: 'pr4-04', domain: 'process', task: 4, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which document shows when each resource is available to work on the project?',
    options: ['Resource calendar', 'Resource breakdown structure', 'Organizational chart', 'RACI chart'],
    answer: 0,
    explanation: 'Resource calendars show working days, shifts, holidays, and availability of each resource.',
  },
  {
    id: 'pr4-05', domain: 'process', task: 4, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Two projects in the same program need the same scarce data scientist at the same time. What should the project manager do?',
    options: [
      'Take the resource for their own project first',
      'Collaborate with the other project manager and program manager to prioritize based on program value and adjust plans',
      'Ask the data scientist to choose',
      'Delay both projects',
    ],
    answer: 1,
    explanation: 'Resource conflicts across projects are resolved at the program or portfolio level based on value and priority, with transparent collaboration.',
  },
  {
    id: 'pr4-06', domain: 'process', task: 4, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What is the recommended size of an agile development team?',
    options: ['3 to 9 members', '15 to 20 members', 'Exactly 12 members', 'At least 25 members'],
    answer: 0,
    explanation: 'Agile guidance recommends small teams (typically 3–9, often "10 or fewer") to keep communication effective.',
  },
  {
    id: 'pr4-07', domain: 'process', task: 4, approach: 'predictive', difficulty: 2, type: 'match',
    stem: 'Match each resource artifact to what it shows.',
    left: ['Resource breakdown structure', 'RACI chart', 'Resource histogram', 'Team charter'],
    right: [
      'Hierarchy of resources by category and type',
      'Who is Responsible, Accountable, Consulted, Informed',
      'Resource usage over time vs. availability',
      'Team values, agreements, and operating guidelines',
    ],
    explanation: 'These artifacts support defining, assigning, and managing resources.',
  },
  {
    id: 'pr4-08', domain: 'process', task: 4, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A team member lacks the skills for an upcoming critical task. There is time before the task starts. What is the BEST approach?',
    options: [
      'Replace the team member',
      'Arrange targeted training or pairing with an expert before the task begins',
      'Assign the task anyway and hope for the best',
      'Remove the task from scope',
    ],
    answer: 1,
    explanation: 'When there is time, developing the team (training, mentoring, pairing) builds capability and morale. Replacement is more disruptive.',
  },

  // ── Task 5: Procurement ──────────────────────────────────────────
  {
    id: 'pr5-01', domain: 'process', task: 5, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which contract type places the MOST cost risk on the seller?',
    options: ['Firm fixed price (FFP)', 'Cost plus fixed fee (CPFF)', 'Time and materials (T&M)', 'Cost plus award fee (CPAF)'],
    answer: 0,
    explanation: 'Under FFP, the seller must deliver for the agreed price regardless of actual costs, so the seller carries the cost risk.',
  },
  {
    id: 'pr5-02', domain: 'process', task: 5, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'The scope of work is unclear and is expected to evolve, but the buyer wants to cap exposure. Which contract approach fits BEST?',
    options: [
      'Firm fixed price for the whole project',
      'Time and materials with a not-to-exceed cap, or an incremental/agile contract with fixed-price sprints',
      'Cost plus percentage of cost',
      'No contract; work on trust',
    ],
    answer: 1,
    explanation: 'Evolving scope suits flexible contracts. A T&M cap or incremental fixed-price iterations balance flexibility with cost control.',
  },
  {
    id: 'pr5-03', domain: 'process', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Before sending a request for proposal, the project manager wants to ensure the buyer can evaluate cost reasonableness. What should be prepared?',
    options: ['Independent cost estimate', 'Bidder conference', 'Make-or-buy analysis', 'Teaming agreement'],
    answer: 0,
    explanation: 'An independent (should-cost) estimate is a benchmark for judging whether proposals are reasonable.',
  },
  {
    id: 'pr5-04', domain: 'process', task: 5, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A CPIF contract has target cost $100K, target fee $10K, and a 70/30 buyer/seller share ratio. Actual cost is $90K. What is the seller\'s fee?',
    options: ['$13,000', '$10,000', '$7,000', '$17,000'],
    answer: 0,
    explanation: 'Underrun = $10K. Seller share 30% = $3K. Fee = $10K + $3K = $13K. Total paid = $90K + $13K = $103K.',
  },
  {
    id: 'pr5-05', domain: 'process', task: 5, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A vendor consistently delivers late. The contract includes performance terms. What should the project manager do FIRST?',
    options: [
      'Terminate the contract',
      'Review vendor performance against the contract and discuss corrective action with the vendor',
      'Withhold all payments',
      'Hire a second vendor without telling the first',
    ],
    answer: 1,
    explanation: 'Evaluating vendor performance and working through the contract\'s terms comes first. Termination and claims are later steps.',
  },
  {
    id: 'pr5-06', domain: 'process', task: 5, approach: 'predictive', difficulty: 1, type: 'match',
    stem: 'Match each procurement document to its purpose.',
    left: ['Request for proposal (RFP)', 'Request for quotation (RFQ)', 'Request for information (RFI)', 'Statement of work (SOW)'],
    right: [
      'Solicit solutions when approach is complex',
      'Solicit price for well-defined items',
      'Gather info about seller capabilities',
      'Describe the work to be procured',
    ],
    explanation: 'RFI gathers information, RFQ asks for price on defined items, RFP asks for proposed solutions, and the SOW describes the work.',
  },
  {
    id: 'pr5-07', domain: 'process', task: 5, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A seller raises a claim that the buyer\'s design change increased their costs. The buyer disagrees. What is the PREFERRED method of resolving the claim?',
    options: ['Litigation', 'Negotiation', 'Terminating the contract', 'Ignoring the claim'],
    answer: 1,
    explanation: 'Negotiation is the preferred way to settle claims and disputes. Alternative dispute resolution and litigation are later steps.',
  },
  {
    id: 'pr5-08', domain: 'process', task: 5, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'All deliverables have been accepted, but one seller has an open invoice dispute. Can the procurement be formally closed?',
    options: [
      'Yes; acceptance of deliverables is enough',
      'No; open claims must be resolved and final settlement completed before closing the procurement',
      'Yes, if the sponsor approves',
      'Only after the warranty period ends',
    ],
    answer: 1,
    explanation: 'Closing a procurement requires formal acceptance and settlement of all claims and payments. Open disputes must be resolved first.',
  },

  // ── Task 6: Finance (EVM etc.) ───────────────────────────────────
  {
    id: 'pr6-01', domain: 'process', task: 6, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'EV = $400K, AC = $500K, PV = $450K. What is the cost performance index (CPI)?',
    options: ['0.80', '0.89', '1.25', '1.11'],
    answer: 0,
    explanation: 'CPI = EV ÷ AC = 400 ÷ 500 = 0.80. The project gets $0.80 of value per $1 spent (over budget).',
  },
  {
    id: 'pr6-02', domain: 'process', task: 6, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'BAC = $1,000K, EV = $400K, AC = $500K. Assuming current cost performance continues, what is the EAC?',
    options: ['$1,250K', '$1,100K', '$900K', '$800K'],
    answer: 0,
    explanation: 'CPI = 0.8. EAC = BAC ÷ CPI = 1000 ÷ 0.8 = $1,250K.',
  },
  {
    id: 'pr6-03', domain: 'process', task: 6, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'What is the difference between contingency reserve and management reserve?',
    options: [
      'Contingency covers identified risks (known-unknowns) and is in the cost baseline; management reserve covers unknown-unknowns and is outside the baseline',
      'Management reserve is part of the cost baseline; contingency is not',
      'They are the same',
      'Contingency is controlled by senior management only',
    ],
    answer: 0,
    explanation: 'Cost baseline = work package estimates + contingency reserves. Budget = cost baseline + management reserve. Using management reserve usually requires approval.',
  },
  {
    id: 'pr6-04', domain: 'process', task: 6, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'BAC = $200K, EV = $80K, AC = $100K. The original variance was atypical and future work is expected at budgeted rate. What is the EAC?',
    options: ['$220K', '$250K', '$200K', '$180K'],
    answer: 0,
    explanation: 'Atypical variance: EAC = AC + (BAC − EV) = 100 + (200 − 80) = $220K.',
  },
  {
    id: 'pr6-05', domain: 'process', task: 6, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'BAC = $500K, EV = $200K, AC = $250K. Management insists the project finish at the original budget. What CPI must be achieved on remaining work (TCPI)?',
    options: ['1.20', '0.83', '1.00', '1.50'],
    answer: 0,
    explanation: 'TCPI = (BAC − EV) ÷ (BAC − AC) = 300 ÷ 250 = 1.20.',
  },
  {
    id: 'pr6-06', domain: 'process', task: 6, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'The S-curve shows cumulative PV, EV, and AC at the current period. What is the status of the project?',
    graphic: {
      kind: 'scurve', title: 'Cumulative cost ($K)',
      pv: [10, 30, 60, 100, 150, 200, 240, 270],
      ev: [8, 24, 48, 80, 120],
      ac: [10, 32, 62, 104, 160],
    },
    options: ['Behind schedule and over budget', 'Ahead of schedule and under budget', 'On schedule and on budget', 'Behind schedule but under budget'],
    answer: 0,
    explanation: 'At period 5: EV 120 < PV 150 → behind schedule (SPI 0.8). AC 160 > EV 120 → over budget (CPI 0.75).',
  },
  {
    id: 'pr6-07', domain: 'process', task: 6, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'How is the budget typically managed on an agile project with a stable team?',
    options: [
      'Detailed bottom-up estimates for every feature at the start',
      'Cost per iteration is roughly fixed (team run rate); scope is adjusted to fit budget and value',
      'Budget is unlimited',
      'Earned value cannot be used at all',
    ],
    answer: 1,
    explanation: 'With a stable team, cost per sprint is predictable. Scope flexes based on value, and the budget can be forecast from the team\'s run rate and velocity.',
  },
  {
    id: 'pr6-08', domain: 'process', task: 6, approach: 'hybrid', difficulty: 2, type: 'dropdown',
    stem: 'Complete the EVM statement.',
    text: 'If SPI is {0} 1.0, the project is behind schedule. If CPI is {1} 1.0, the project is under budget.',
    blanks: [
      { options: ['less than', 'greater than', 'equal to'], answer: 0 },
      { options: ['less than', 'greater than', 'equal to'], answer: 1 },
    ],
    explanation: 'SPI = EV/PV < 1 means less work done than planned. CPI = EV/AC > 1 means more value earned than spent.',
  },
  {
    id: 'pr6-09', domain: 'process', task: 6, approach: 'predictive', difficulty: 3, type: 'hotspot',
    stem: 'Tap the FIRST period in which the project became over budget (AC greater than EV).',
    graphic: {
      kind: 'scurve', title: 'Cumulative cost ($K)',
      pv: [20, 50, 90, 140, 190, 230],
      ev: [20, 52, 88, 130, 175],
      ac: [18, 48, 92, 140, 190],
    },
    answer: 'p3',
    explanation: 'Period 1: AC 18 < EV 20. Period 2: 48 < 52. Period 3: AC 92 > EV 88, the first overrun.',
  },

  // ── Task 7: Quality ──────────────────────────────────────────────
  {
    id: 'pr7-01', domain: 'process', task: 7, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'Which is an example of cost of conformance?',
    options: ['Training and testing', 'Rework', 'Warranty claims', 'Lost business due to defects'],
    answer: 0,
    explanation: 'Cost of conformance = prevention (training) + appraisal (testing). Rework, warranty, and lost business are costs of nonconformance (failure).',
  },
  {
    id: 'pr7-02', domain: 'process', task: 7, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A control chart shows seven consecutive points above the mean, all within control limits. What does this indicate?',
    options: [
      'The process is in control; no action needed',
      'The process may be out of control (rule of seven); investigate for assignable cause',
      'The control limits are wrong',
      'The specification limits must be changed',
    ],
    answer: 1,
    explanation: 'The rule of seven: seven consecutive points on one side of the mean suggests a non-random pattern. Investigate.',
  },
  {
    id: 'pr7-03', domain: 'process', task: 7, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What does the Definition of Done (DoD) ensure on an agile team?',
    options: [
      'All increments meet a shared, consistent quality standard',
      'The sprint finishes on time',
      'The product owner approves the budget',
      'The team never has defects',
    ],
    answer: 0,
    explanation: 'The DoD is the team\'s shared quality checklist. An increment is not done until it meets every item.',
  },
  {
    id: 'pr7-04', domain: 'process', task: 7, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'A Pareto chart of defects shows that 3 of 12 defect types account for 80% of occurrences. What should the team do?',
    options: [
      'Fix all 12 types equally',
      'Focus improvement efforts on the 3 dominant defect types first',
      'Ignore the chart',
      'Focus on the least frequent types',
    ],
    answer: 1,
    explanation: 'Pareto (80/20) analysis helps prioritize the "vital few" causes that drive most problems.',
  },
  {
    id: 'pr7-05', domain: 'process', task: 7, approach: 'predictive', difficulty: 2, type: 'match',
    stem: 'Match each quality tool to its use.',
    left: ['Ishikawa (fishbone) diagram', 'Control chart', 'Scatter diagram', 'Histogram'],
    right: [
      'Identify potential root causes',
      'Determine if a process is stable over time',
      'Show the relationship between two variables',
      'Show the frequency distribution of data',
    ],
    explanation: 'These are classic quality tools used in Manage and Control Quality.',
  },
  {
    id: 'pr7-06', domain: 'process', task: 7, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A medical device project must meet strict regulatory standards. Late audits keep finding documentation gaps. What is the BEST preventive approach?',
    options: [
      'Increase final inspection',
      'Build compliance checks into the Definition of Done and the quality management plan, with regular quality reviews',
      'Ask regulators to relax standards',
      'Hire more auditors at the end',
    ],
    answer: 1,
    explanation: 'Quality is planned and built in, not inspected in. Embedding regulatory requirements in ongoing processes prevents late findings.',
  },
  {
    id: 'pr7-07', domain: 'process', task: 7, approach: 'agile', difficulty: 2, type: 'multi',
    stem: 'Which TWO practices build quality into agile development?',
    options: ['Test-driven development (TDD)', 'Continuous integration', 'Testing only after the final release', 'Skipping code reviews to save time', 'Waiting for user complaints'],
    answer: [0, 1],
    explanation: 'TDD and continuous integration catch defects early and continuously, which keeps the cost of quality low.',
  },
  {
    id: 'pr7-08', domain: 'process', task: 7, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'What is the difference between precision and accuracy?',
    options: [
      'Precision is consistency of repeated measures; accuracy is closeness to the true value',
      'They mean the same thing',
      'Accuracy is consistency; precision is correctness',
      'Precision only applies to software',
    ],
    answer: 0,
    explanation: 'Precise measurements cluster tightly. Accurate measurements are close to the target. A process can be precise but not accurate.',
  },

  // ── Task 8: Schedule ─────────────────────────────────────────────
  {
    id: 'pr8-01', domain: 'process', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Using the network table, what is the duration of the critical path?',
    graphic: {
      kind: 'table', title: 'Activity list',
      headers: ['Activity', 'Duration (days)', 'Predecessor'],
      rows: [['A', 3, '—'], ['B', 5, 'A'], ['C', 2, 'A'], ['D', 4, 'C'], ['E', 3, 'B, D']],
    },
    options: ['11 days', '12 days', '9 days', '17 days'],
    answer: 1,
    explanation: 'Paths: A-B-E = 3+5+3 = 11; A-C-D-E = 3+2+4+3 = 12. The longest path is the critical path: 12 days.',
  },
  {
    id: 'pr8-02', domain: 'process', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'Using the same network, how much total float does activity B have?',
    graphic: {
      kind: 'table', title: 'Activity list',
      headers: ['Activity', 'Duration (days)', 'Predecessor'],
      rows: [['A', 3, '—'], ['B', 5, 'A'], ['C', 2, 'A'], ['D', 4, 'C'], ['E', 3, 'B, D']],
    },
    options: ['1 day', '0 days', '2 days', '3 days'],
    answer: 0,
    explanation: 'Critical path A-C-D-E = 12 days. Path through B = 11 days. B\'s float = 12 − 11 = 1 day.',
  },
  {
    id: 'pr8-03', domain: 'process', task: 8, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'The project is behind schedule. The team proposes running design and build in parallel. This technique is called:',
    options: ['Fast tracking', 'Crashing', 'Resource leveling', 'Rolling wave planning'],
    answer: 0,
    explanation: 'Fast tracking overlaps activities normally done in sequence, which adds risk. Crashing adds resources, which adds cost.',
  },
  {
    id: 'pr8-04', domain: 'process', task: 8, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'A PERT estimate has optimistic = 4 days, most likely = 7 days, pessimistic = 16 days. What is the expected duration?',
    options: ['8 days', '9 days', '7 days', '10 days'],
    answer: 0,
    explanation: 'Beta/PERT: (O + 4M + P) ÷ 6 = (4 + 28 + 16) ÷ 6 = 48 ÷ 6 = 8 days.',
  },
  {
    id: 'pr8-05', domain: 'process', task: 8, approach: 'agile', difficulty: 2, type: 'hotspot',
    stem: 'The team noticed a blocker that halted progress. Tap the day on the burndown where work stopped burning down.',
    graphic: {
      kind: 'burndown', title: 'Sprint burndown (story points)', days: 10, total: 40,
      actual: [40, 36, 32, 32, 32, 32, 26, 20, 14, null, null],
      unit: 'pts',
    },
    answer: 'd3',
    explanation: 'Remaining work was 32 at day 2 and stayed at 32 through day 5. Day 3 is the first day with no burn, a sign a blocker started there.',
  },
  {
    id: 'pr8-06', domain: 'process', task: 8, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'A team\'s velocity over the last four sprints was 28, 32, 30, and 30. The remaining release backlog is 150 points. How many more sprints are needed?',
    options: ['5 sprints', '4 sprints', '6 sprints', '3 sprints'],
    answer: 0,
    explanation: 'Average velocity = 120 ÷ 4 = 30. 150 ÷ 30 = 5 sprints.',
  },
  {
    id: 'pr8-07', domain: 'process', task: 8, approach: 'predictive', difficulty: 1, type: 'match',
    stem: 'Match each dependency type to an example.',
    left: ['Mandatory', 'Discretionary', 'External', 'Internal'],
    right: [
      'Foundation must be poured before walls are built',
      'Team prefers to finish design before prototyping',
      'Waiting on a government permit',
      'Testing waits on the team\'s own build',
    ],
    explanation: 'Mandatory = required by contract or physics (hard logic). Discretionary = preferred (soft logic). External = outside the project. Internal = within the project.',
  },
  {
    id: 'pr8-08', domain: 'process', task: 8, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'A hybrid project has a predictive hardware stream and an agile software stream. Software sprint outputs must integrate with hardware milestones. What is the BEST way to coordinate the schedule?',
    options: [
      'Convert all work to sprints',
      'Use a high-level integrated roadmap with milestone dependencies, and align sprint goals to hardware milestones',
      'Let each stream schedule independently',
      'Delay software until hardware is complete',
    ],
    answer: 1,
    explanation: 'Hybrid schedules connect the approaches through integrated roadmaps and milestones while each stream keeps its own planning cadence.',
  },
  {
    id: 'pr8-09', domain: 'process', task: 8, approach: 'agile', difficulty: 1, type: 'single',
    stem: 'What does a story point estimate represent?',
    options: [
      'Relative size and complexity of work compared to other items',
      'Exact number of hours',
      'Cost in dollars',
      'Number of people needed',
    ],
    answer: 0,
    explanation: 'Story points are relative estimates of effort, complexity, and uncertainty, not hours.',
  },

  // ── Task 9: Evaluate project status ──────────────────────────────
  {
    id: 'pr9-01', domain: 'process', task: 9, approach: 'agile', difficulty: 2, type: 'hotspot',
    stem: 'Work is piling up and flow has slowed. Tap the column that is the bottleneck.',
    graphic: {
      kind: 'kanban', title: 'Team Kanban board',
      columns: [
        { id: 'todo', name: 'To Do', cards: 8 },
        { id: 'dev', name: 'Dev', wip: 4, cards: 3 },
        { id: 'review', name: 'Review', wip: 3, cards: 6 },
        { id: 'test', name: 'Test', wip: 3, cards: 1 },
        { id: 'done', name: 'Done', cards: 12 },
      ],
    },
    answer: 'review',
    explanation: 'Review has 6 cards against a WIP limit of 3, while Test downstream is nearly empty. Work is stuck in Review, so that is the bottleneck.',
  },
  {
    id: 'pr9-02', domain: 'process', task: 9, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'SPI = 1.1 and CPI = 0.9. What is the project status?',
    options: ['Ahead of schedule, over budget', 'Behind schedule, under budget', 'Ahead of schedule, under budget', 'Behind schedule, over budget'],
    answer: 0,
    explanation: 'SPI > 1 → ahead of schedule. CPI < 1 → over budget.',
  },
  {
    id: 'pr9-03', domain: 'process', task: 9, approach: 'hybrid', difficulty: 2, type: 'single',
    stem: 'Team members keep creating documents that no one reads, while stakeholders cannot find the status they need. What should the project manager do?',
    options: [
      'Mandate more documents',
      'Review and tailor the artifacts to what stakeholders actually use, and make key artifacts easy to access',
      'Stop all documentation',
      'Ask stakeholders to read everything',
    ],
    answer: 1,
    explanation: 'The ECO asks the PM to identify and tailor needed artifacts and keep checking whether artifact management is working.',
  },
  {
    id: 'pr9-04', domain: 'process', task: 9, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'What is the difference between lead time and cycle time in Kanban?',
    options: [
      'Lead time is from request to delivery; cycle time is from work start to finish',
      'They are identical',
      'Cycle time includes waiting in the backlog; lead time does not',
      'Lead time only applies to manufacturing',
    ],
    answer: 0,
    explanation: 'Lead time is what the customer sees (request to delivery). Cycle time is the team\'s active work time (start to done).',
  },
  {
    id: 'pr9-05', domain: 'process', task: 9, approach: 'agile', difficulty: 3, type: 'hotspot',
    stem: 'Velocity has been stable except for one sprint where the team took on unplanned production incidents. Tap that sprint.',
    graphic: {
      kind: 'bars', title: 'Velocity per sprint', labels: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6'],
      values: [28, 31, 30, 14, 29, 32], unit: 'pts', line: 30, lineLabel: 'avg',
    },
    answer: 'b3',
    explanation: 'Sprint 4 (14 points) is a clear outlier against a stable ~30 point average, which points to a disruption.',
  },
  {
    id: 'pr9-06', domain: 'process', task: 9, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'The variance analysis shows that a work package is 15% over its cost estimate, beyond the 10% threshold in the cost management plan. What should the project manager do?',
    options: [
      'Nothing; variances are normal',
      'Analyze the cause, assess impact, and take corrective action, raising a change request if needed',
      'Re-baseline immediately without approval',
      'Hide the variance until the next phase',
    ],
    answer: 1,
    explanation: 'Exceeding a control threshold triggers root-cause analysis and corrective action through integrated change control.',
  },
  {
    id: 'pr9-07', domain: 'process', task: 9, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'Which of the following is the BEST way to communicate project status to a large, diverse group of stakeholders?',
    options: ['A visual dashboard with key metrics, updated regularly and easy to access', 'A 50-page detailed report', 'Ad hoc phone calls', 'Verbal updates in hallway conversations'],
    answer: 0,
    explanation: 'Dashboards give a concise, consistent, accessible view of status for many audiences.',
  },
  {
    id: 'pr9-08', domain: 'process', task: 9, approach: 'agile', difficulty: 3, type: 'single',
    stem: 'A release burnup chart shows the scope line rising as fast as the completed work line. What does this indicate?',
    options: [
      'The release is ahead of schedule',
      'Scope growth is offsetting progress, so the release date will not converge without scope decisions',
      'The team velocity is decreasing',
      'The chart is broken',
    ],
    answer: 1,
    explanation: 'Burnups separate scope from progress. If total scope keeps rising at the same rate as completed work, the lines never meet. Raise this with the product owner.',
  },

  // ── Task 10: Project closure ─────────────────────────────────────
  {
    id: 'pr10-01', domain: 'process', task: 10, approach: 'predictive', difficulty: 1, type: 'single',
    stem: 'What is the FIRST step in closing a project?',
    options: [
      'Obtain formal acceptance of deliverables',
      'Release the team',
      'Archive the documents',
      'Celebrate success',
    ],
    answer: 0,
    explanation: 'Formal acceptance from the customer or sponsor confirms the project has met its objectives. Other closure activities follow.',
  },
  {
    id: 'pr10-02', domain: 'process', task: 10, approach: 'predictive', difficulty: 2, type: 'single',
    stem: 'A project is terminated early by the sponsor due to a change in strategy. What should the project manager do?',
    options: [
      'Stop all work and leave immediately',
      'Perform closing activities: document the status, deliverables completed, lessons learned, and release resources',
      'Continue working until the original end date',
      'Hand everything to the sponsor without documentation',
    ],
    answer: 1,
    explanation: 'Even terminated projects need formal closure: documenting the level of completion, archiving, capturing lessons, and closing contracts and resources.',
  },
  {
    id: 'pr10-03', domain: 'process', task: 10, approach: 'hybrid', difficulty: 2, type: 'multi',
    stem: 'Which TWO activities are part of validating readiness for transition to operations?',
    options: [
      'Confirm operations has been trained and has the runbooks',
      'Verify the transition acceptance criteria are met',
      'Start a new project charter',
      'Increase the project budget',
      'Delete the project schedule',
    ],
    answer: [0, 1],
    explanation: 'Before handover, confirm the receiving organization is ready (training, documentation) and that agreed transition criteria are met.',
  },
  {
    id: 'pr10-04', domain: 'process', task: 10, approach: 'agile', difficulty: 2, type: 'single',
    stem: 'An agile project ends after the final release. What is a key closing activity?',
    options: [
      'A final retrospective to capture lessons for the organization',
      'Rewriting all user stories in detail',
      'Extending the last sprint',
      'Resetting velocity to zero',
    ],
    answer: 0,
    explanation: 'A final retrospective captures lessons learned and improvements for future teams and organizational knowledge.',
  },
  {
    id: 'pr10-05', domain: 'process', task: 10, approach: 'predictive', difficulty: 3, type: 'single',
    stem: 'The customer refuses to sign acceptance, citing a minor defect that is outside the agreed acceptance criteria. What should the project manager do?',
    options: [
      'Close the project without acceptance',
      'Review the acceptance criteria with the customer, show compliance, and handle the new request through change control',
      'Fix the defect for free without documenting it',
      'Escalate to legal immediately',
    ],
    answer: 1,
    explanation: 'Acceptance is based on agreed criteria. Show they are met and handle new requests through change control. Escalate only if needed.',
  },
  {
    id: 'pr10-06', domain: 'process', task: 10, approach: 'hybrid', difficulty: 1, type: 'single',
    stem: 'When should final lessons learned be transferred to the organizational process assets?',
    options: ['During project or phase closure', 'Before the charter is signed', 'Only if the project failed', 'Never; they are confidential'],
    answer: 0,
    explanation: 'Lessons are gathered throughout. At closure they are finalized and added to the organization\'s lessons learned repository.',
  },
  {
    id: 'pr10-07', domain: 'process', task: 10, approach: 'predictive', difficulty: 2, type: 'dropdown',
    stem: 'Complete the closing sequence.',
    text: 'Before closing the project, the project manager must {0} all procurements and then {1} project resources.',
    blanks: [
      { options: ['close', 'renew', 'ignore'], answer: 0 },
      { options: ['release', 'hire', 'level'], answer: 0 },
    ],
    explanation: 'Close procurements (settle contracts) and release resources as part of the Close Project or Phase activities.',
  },
  {
    id: 'pr10-08', domain: 'process', task: 10, approach: 'hybrid', difficulty: 3, type: 'single',
    stem: 'Phase 1 of a multi-phase program is complete. The sponsor wants to start Phase 2 immediately. What should the project manager ensure FIRST?',
    options: [
      'Phase 1 exit criteria are met and approved, with a go/no-go decision for Phase 2',
      'Phase 2 starts without review to save time',
      'All Phase 1 team members are released',
      'The Phase 2 budget is doubled',
    ],
    answer: 0,
    explanation: 'Phase gates confirm exit criteria and continued business value before committing resources to the next phase.',
  },
];
